// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.offset_gemm --emit-cu.
// family=cute_grouped_sm80_ad backend=cute_grouped_sm80 op=ad_gather_scatter grouped=true
// tile_tag=Tile128x128x64

#if defined(WARPCONVNET_SM80_ENABLED)

#include "include/cute_gemm_explicit_sm80.cuh"

namespace warpconvnet {
namespace cute_gemm {

INSTANTIATE_GROUPED_ALL_DTYPES(Tile128x128x64)

}  // namespace cute_gemm
}  // namespace warpconvnet

#endif  // WARPCONVNET_SM80_ENABLED
