// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.offset_gemm --emit-cu.
// family=cute_sm90 backend=cute_sm90 op=ad_gather_scatter grouped=false
// tile_tag=SM90_Tile256x128x64

#if defined(WARPCONVNET_SM90_ENABLED)

#include "include/cute_gemm_explicit_sm90.cuh"

namespace warpconvnet {
namespace cute_gemm {

INSTANTIATE_SM90_ALL_DTYPES(SM90_Tile256x128x64)
INSTANTIATE_SM90_ALL_DTYPES_BF16(SM90_Tile256x128x64)

}  // namespace cute_gemm
}  // namespace warpconvnet

#endif  // WARPCONVNET_SM90_ENABLED
