// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.offset_gemm --emit-cu.
// family=cute_grouped_sm90_staged backend=cute_grouped_sm90 op=ad_gather_scatter grouped=true
// tile_tag=SM90_Tile128x256x64

#if defined(WARPCONVNET_SM90_ENABLED)

#include "include/cute_gemm_explicit_sm90.cuh"

namespace warpconvnet {
namespace cute_gemm {

INSTANTIATE_SM90_STAGED_GROUPED(cutlass::half_t, float, SM90_Tile128x256x64)
INSTANTIATE_SM90_STAGED_GROUPED(cutlass::half_t, cutlass::half_t, SM90_Tile128x256x64)
#ifndef DISABLE_BFLOAT16
INSTANTIATE_SM90_STAGED_GROUPED(cutlass::bfloat16_t, float, SM90_Tile128x256x64)
INSTANTIATE_SM90_STAGED_GROUPED(cutlass::bfloat16_t, cutlass::bfloat16_t, SM90_Tile128x256x64)
#endif  // DISABLE_BFLOAT16

}  // namespace cute_gemm
}  // namespace warpconvnet

#endif  // WARPCONVNET_SM90_ENABLED
