// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.offset_gemm --emit-cu.
// family=implicit_split_k backend=implicit_split_k op=ad_gather_scatter grouped=false split_k=true
// dtype=(bf16,bf16,bf16) block_size=16 kernel_variant=basic itype=int32 tile_id=628 tier=production

#include "include/implicit_gemm_split_k_explicit.cuh"

namespace warpconvnet {
namespace split_k_implicit_gemm {

INSTANTIATE_IMPLICIT_GEMM_SPLIT_K(__nv_bfloat16, __nv_bfloat16, __nv_bfloat16, int, 16, basic);

}  // namespace split_k_implicit_gemm
}  // namespace warpconvnet
