// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm codegen
// Shared launch wrappers and dispatch templates for fwd/dgrad/wgrad.
#pragma once

#include <cuda_runtime.h>

#include <cute/tensor.hpp>

namespace warpgemm {

// L2 persistence: pin weight tensor (ptr_B) in L2 cache.
inline void set_l2_persist_weight(const void *ptr_B, size_t weight_bytes, cudaStream_t stream) {
  cudaStreamAttrValue attr = {};
  attr.accessPolicyWindow.base_ptr = const_cast<void *>(ptr_B);
  attr.accessPolicyWindow.num_bytes = weight_bytes;
  attr.accessPolicyWindow.hitRatio = 1.0f;
  attr.accessPolicyWindow.hitProp = cudaAccessPropertyPersisting;
  attr.accessPolicyWindow.missProp = cudaAccessPropertyStreaming;
  cudaStreamSetAttribute(stream, cudaStreamAttributeAccessPolicyWindow, &attr);
}

inline void reset_l2_persist(cudaStream_t stream) {
  cudaStreamAttrValue attr = {};
  attr.accessPolicyWindow.num_bytes = 0;
  cudaStreamSetAttribute(stream, cudaStreamAttributeAccessPolicyWindow, &attr);
}

// Forward/Dgrad launch wrapper
template <class Kernel>
__global__ __launch_bounds__(
    Kernel::MaxThreadsPerBlock,
    Kernel::MinBlocksPerMultiprocessor) void launch_mask_gemm(const typename Kernel::ElementInput
                                                                  *ptr_A,
                                                              const typename Kernel::ElementInput
                                                                  *ptr_B,
                                                              typename Kernel::ElementOutput *ptr_D,
                                                              const int *pair_table,
                                                              const uint32_t *pair_mask,
                                                              const int *mask_argsort,
                                                              int N_in,
                                                              int N_out,
                                                              int C_in,
                                                              int C_out,
                                                              int K,
                                                              float alpha,
                                                              int stride_A,
                                                              int stride_D,
                                                              int identity_offset) {
  extern __shared__ char smem[];
  Kernel{}(ptr_A,
           ptr_B,
           ptr_D,
           pair_table,
           pair_mask,
           mask_argsort,
           N_in,
           N_out,
           C_in,
           C_out,
           K,
           alpha,
           stride_A,
           stride_D,
           identity_offset,
           smem);
}

// Persistent kernel launch wrapper: kernel struct has work_counter in operator()
template <class Kernel>
__global__ __launch_bounds__(Kernel::MaxThreadsPerBlock, 1) void launch_mask_gemm_persistent(
    const typename Kernel::ElementInput *ptr_A,
    const typename Kernel::ElementInput *ptr_B,
    typename Kernel::ElementOutput *ptr_D,
    const int *pair_table,
    const uint32_t *pair_mask,
    const int *mask_argsort,
    int N_in,
    int N_out,
    int C_in,
    int C_out,
    int K,
    float alpha,
    int stride_A,
    int stride_D,
    int identity_offset,
    int *work_counter,
    int total_tiles) {
  extern __shared__ char smem[];
  Kernel{}(ptr_A,
           ptr_B,
           ptr_D,
           pair_table,
           pair_mask,
           mask_argsort,
           N_in,
           N_out,
           C_in,
           C_out,
           K,
           alpha,
           stride_A,
           stride_D,
           identity_offset,
           smem,
           work_counter,
           total_tiles);
}

// Persistent dispatch: grid = num_SMs, each CTA claims tiles dynamically
template <class Kernel>
int run_mask_gemm_persistent(const void *a,
                             const void *b,
                             void *d,
                             const int *pair_table,
                             const uint32_t *pair_mask,
                             const int *mask_argsort,
                             int N_in,
                             int N_out,
                             int C_in,
                             int C_out,
                             int K,
                             float alpha,
                             int groups = 1,
                             int *work_counter = nullptr,
                             cudaStream_t stream = 0) {
  using ElementInput = typename Kernel::ElementInput;
  constexpr int TileM = cute::size<0>(typename Kernel::TileShape{});
  constexpr int TileN = cute::size<1>(typename Kernel::TileShape{});
  constexpr size_t smem_size = Kernel::SharedStorageSize;
  if (N_out == 0 || C_in == 0 || C_out == 0) return 0;
  int m_tiles = (N_out + TileM - 1) / TileM;
  int n_tiles = (C_out + TileN - 1) / TileN;
  int total_tiles = m_tiles * n_tiles;

  int num_sms = 0;
  cudaDeviceGetAttribute(&num_sms, cudaDevAttrMultiProcessorCount, 0);
  int grid = (total_tiles < num_sms) ? total_tiles : num_sms;

  cudaMemsetAsync(work_counter, 0, sizeof(int), stream);

  if (smem_size > 48 * 1024) {
    cudaFuncSetAttribute(launch_mask_gemm_persistent<Kernel>,
                         cudaFuncAttributeMaxDynamicSharedMemorySize,
                         smem_size);
  }

  size_t weight_bytes = (size_t)K * C_in * C_out * sizeof(ElementInput);
  set_l2_persist_weight(b, weight_bytes, stream);

  launch_mask_gemm_persistent<Kernel><<<grid, Kernel::MaxThreadsPerBlock, smem_size, stream>>>(
      reinterpret_cast<const ElementInput *>(a),
      reinterpret_cast<const ElementInput *>(b),
      reinterpret_cast<typename Kernel::ElementOutput *>(d),
      pair_table,
      pair_mask,
      mask_argsort,
      N_in,
      N_out,
      C_in,
      C_out,
      K,
      alpha,
      C_in,
      C_out,
      -1,  // stride_A, stride_D, identity_offset
      work_counter,
      total_tiles);
  auto err = cudaGetLastError();
  reset_l2_persist(stream);
  return err == cudaSuccess ? 0 : -1;
}

// Forward dispatch
template <class Kernel>
int run_mask_gemm(const void *a,
                  const void *b,
                  void *d,
                  const int *pair_table,
                  const uint32_t *pair_mask,
                  const int *mask_argsort,
                  int N_in,
                  int N_out,
                  int C_in,
                  int C_out,
                  int K,
                  float alpha,
                  int groups = 1,
                  int identity_offset = -1,
                  cudaStream_t stream = 0) {
  using ElementInput = typename Kernel::ElementInput;
  constexpr int TileM = cute::size<0>(typename Kernel::TileShape{});
  constexpr int TileN = cute::size<1>(typename Kernel::TileShape{});
  constexpr size_t smem_size = Kernel::SharedStorageSize;
  // C_in/C_out are per-group values; stride_A/stride_D are full row strides
  int stride_A = C_in * groups;
  int stride_D = C_out * groups;
  if (N_out == 0 || C_in == 0 || C_out == 0) return 0;
  int m_tiles = (N_out + TileM - 1) / TileM;
  int n_tiles = (C_out + TileN - 1) / TileN;
  dim3 grid(m_tiles * n_tiles, 1, groups);
  if (smem_size > 48 * 1024) {
    auto err = cudaFuncSetAttribute(
        launch_mask_gemm<Kernel>, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_size);
    if (err != cudaSuccess) return -1;
  }
  // Pin weight in L2 (weight = K * groups * C_in * C_out elements)
  size_t weight_bytes = (size_t)K * groups * C_in * C_out * sizeof(ElementInput);
  set_l2_persist_weight(b, weight_bytes, stream);

  launch_mask_gemm<Kernel><<<grid, Kernel::MaxThreadsPerBlock, smem_size, stream>>>(
      reinterpret_cast<const ElementInput *>(a),
      reinterpret_cast<const ElementInput *>(b),
      reinterpret_cast<typename Kernel::ElementOutput *>(d),
      pair_table,
      pair_mask,
      mask_argsort,
      N_in,
      N_out,
      C_in,
      C_out,
      K,
      alpha,
      stride_A,
      stride_D,
      identity_offset);
  auto err = cudaGetLastError();
  reset_l2_persist(stream);
  return err == cudaSuccess ? 0 : -1;
}

// Dgrad dispatch
// C_in, C_out are per-group values. groups defaults to 1.
template <class Kernel>
int run_mask_gemm_dgrad(const void *a,
                        const void *b,
                        void *d,
                        const int *pair_table,
                        const uint32_t *pair_mask,
                        const int *mask_argsort,
                        int N_in,
                        int N_out,
                        int C_in,
                        int C_out,
                        int K,
                        float alpha,
                        int groups = 1,
                        cudaStream_t stream = 0) {
  using ElementInput = typename Kernel::ElementInput;
  constexpr int TileM = cute::size<0>(typename Kernel::TileShape{});
  constexpr int TileN = cute::size<1>(typename Kernel::TileShape{});
  constexpr size_t smem_size = Kernel::SharedStorageSize;
  int stride_A = C_out * groups;  // grad_output row stride
  int stride_D = C_in * groups;   // grad_input row stride
  if (N_in == 0 || C_in == 0 || C_out == 0) return 0;
  int m_tiles = (N_in + TileM - 1) / TileM;
  int n_tiles = (C_in + TileN - 1) / TileN;
  dim3 grid(m_tiles * n_tiles, Kernel::SplitOffsets, groups);
  if (smem_size > 48 * 1024) {
    auto err = cudaFuncSetAttribute(
        launch_mask_gemm<Kernel>, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_size);
    if (err != cudaSuccess) return -1;
  }
  // Pin weight in L2 for dgrad
  size_t weight_bytes = (size_t)K * groups * C_in * C_out * sizeof(ElementInput);
  set_l2_persist_weight(b, weight_bytes, stream);

  launch_mask_gemm<Kernel><<<grid, Kernel::MaxThreadsPerBlock, smem_size, stream>>>(
      reinterpret_cast<const ElementInput *>(a),
      reinterpret_cast<const ElementInput *>(b),
      reinterpret_cast<typename Kernel::ElementOutput *>(d),
      pair_table,
      pair_mask,
      mask_argsort,
      N_in,
      N_out,
      C_in,
      C_out,
      K,
      alpha,
      stride_A,
      stride_D,
      -1);  // identity_offset=-1 (dgrad has no identity shortcut)
  auto dgrad_err = cudaGetLastError();
  reset_l2_persist(stream);
  return dgrad_err == cudaSuccess ? 0 : -1;
}

// Wgrad launch wrapper
template <class Kernel>
__global__ __launch_bounds__(
    Kernel::MaxThreadsPerBlock,
    Kernel::
        MinBlocksPerMultiprocessor) void launch_mask_gemm_wgrad(const typename Kernel::ElementInput
                                                                    *ptr_A,
                                                                const typename Kernel::ElementInput
                                                                    *ptr_B,
                                                                typename Kernel::ElementOutput
                                                                    *ptr_D,
                                                                const int *pair_table,
                                                                const uint32_t *pair_mask,
                                                                const int *mask_argsort,
                                                                const uint32_t *reduced_mask,
                                                                int N_in,
                                                                int N_out,
                                                                int C_in,
                                                                int C_out,
                                                                int K,
                                                                float alpha,
                                                                int stride_A,
                                                                int stride_B) {
  extern __shared__ char smem[];
  Kernel{}(ptr_A,
           ptr_B,
           ptr_D,
           pair_table,
           pair_mask,
           mask_argsort,
           reduced_mask,
           N_in,
           N_out,
           C_in,
           C_out,
           K,
           alpha,
           stride_A,
           stride_B,
           smem);
}

// Wgrad dispatch
// C_in, C_out are per-group values. groups defaults to 1.
template <class Kernel>
int run_mask_gemm_wgrad(const void *a,
                        const void *b,
                        void *d,
                        const int *pair_table,
                        const uint32_t *pair_mask,
                        const int *mask_argsort,
                        const uint32_t *reduced_mask,
                        int N_in,
                        int N_out,
                        int C_in,
                        int C_out,
                        int K,
                        float alpha,
                        int split_k,
                        int groups = 1,
                        cudaStream_t stream = 0) {
  using ElementInput = typename Kernel::ElementInput;
  constexpr int TileM = cute::size<0>(typename Kernel::TileShape{});
  constexpr int TileN = cute::size<1>(typename Kernel::TileShape{});
  constexpr size_t smem_size = Kernel::SharedStorageSize;
  int stride_A = C_in * groups;   // input row stride
  int stride_B = C_out * groups;  // grad_output row stride
  if (C_in == 0 || C_out == 0 || N_out == 0) return 0;
  int m_tiles = (C_in + TileM - 1) / TileM;
  int n_tiles = (C_out + TileN - 1) / TileN;
  dim3 grid(m_tiles * n_tiles, groups * K, split_k);
  if (smem_size > 48 * 1024) {
    auto err = cudaFuncSetAttribute(
        launch_mask_gemm_wgrad<Kernel>, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_size);
    if (err != cudaSuccess) return -1;
  }
  launch_mask_gemm_wgrad<Kernel><<<grid, Kernel::MaxThreadsPerBlock, smem_size, stream>>>(
      reinterpret_cast<const ElementInput *>(a),
      reinterpret_cast<const ElementInput *>(b),
      reinterpret_cast<typename Kernel::ElementOutput *>(d),
      pair_table,
      pair_mask,
      mask_argsort,
      reduced_mask,
      N_in,
      N_out,
      C_in,
      C_out,
      K,
      alpha,
      stride_A,
      stride_B);
  return cudaGetLastError() == cudaSuccess ? 0 : -1;
}

}  // namespace warpgemm
