// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.

#pragma once

#include "cute_gemm_launch.h"

namespace warpconvnet {
namespace cute_gemm {

// ============================================================================
// AD gather-scatter (non-grouped)
// ============================================================================

#define INSTANTIATE_CUTE_AD_GS(ElemIn, ElemOut, TileTag)                                     \
  template int run_cute_gemm_ad_gather_scatter<ElemIn, gemm::TileTag, ElemOut>(const void *, \
                                                                               const void *, \
                                                                               const void *, \
                                                                               void *,       \
                                                                               const int *,  \
                                                                               const int *,  \
                                                                               int,          \
                                                                               int,          \
                                                                               int,          \
                                                                               int,          \
                                                                               int,          \
                                                                               float,        \
                                                                               float);

#define INSTANTIATE_CUTE_TRAB(ElemIn, ElemOut, TileTag)                                \
  template int run_cute_gemm_trAB_gather<ElemIn, gemm::TileTag, ElemOut>(const void *, \
                                                                         const void *, \
                                                                         const void *, \
                                                                         void *,       \
                                                                         const int *,  \
                                                                         const int *,  \
                                                                         int,          \
                                                                         int,          \
                                                                         int,          \
                                                                         int,          \
                                                                         int,          \
                                                                         float,        \
                                                                         float);

// Instantiate AD + TrAB for all 4 (input, output) dtype pairs at one tile.
#define INSTANTIATE_ALL_DTYPES(TileTag)                                     \
  INSTANTIATE_CUTE_AD_GS(cutlass::half_t, float, TileTag)                   \
  INSTANTIATE_CUTE_AD_GS(cutlass::half_t, cutlass::half_t, TileTag)         \
  INSTANTIATE_CUTE_AD_GS(cutlass::bfloat16_t, float, TileTag)               \
  INSTANTIATE_CUTE_AD_GS(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag) \
  INSTANTIATE_CUTE_TRAB(cutlass::half_t, float, TileTag)                    \
  INSTANTIATE_CUTE_TRAB(cutlass::half_t, cutlass::half_t, TileTag)          \
  INSTANTIATE_CUTE_TRAB(cutlass::bfloat16_t, float, TileTag)                \
  INSTANTIATE_CUTE_TRAB(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

// ----------------------------------------------------------------------------
// E1 sibling macros — `_pcoff` (use_precomputed_offsets=True). Hoists
// gather-index __ldg out of the K-loop. Mirror of mask-side
// use_precomputed_offsets composition. Templates pending in warpconvnet.
// ----------------------------------------------------------------------------

#define INSTANTIATE_CUTE_AD_GS_PCOFF(ElemIn, ElemOut, TileTag)                                     \
  template int run_cute_gemm_ad_gather_scatter_pcoff<ElemIn, gemm::TileTag, ElemOut>(const void *, \
                                                                                     const void *, \
                                                                                     const void *, \
                                                                                     void *,       \
                                                                                     const int *,  \
                                                                                     const int *,  \
                                                                                     int,          \
                                                                                     int,          \
                                                                                     int,          \
                                                                                     int,          \
                                                                                     int,          \
                                                                                     float,        \
                                                                                     float);

#define INSTANTIATE_CUTE_TRAB_PCOFF(ElemIn, ElemOut, TileTag)                                \
  template int run_cute_gemm_trAB_gather_pcoff<ElemIn, gemm::TileTag, ElemOut>(const void *, \
                                                                               const void *, \
                                                                               const void *, \
                                                                               void *,       \
                                                                               const int *,  \
                                                                               const int *,  \
                                                                               int,          \
                                                                               int,          \
                                                                               int,          \
                                                                               int,          \
                                                                               int,          \
                                                                               float,        \
                                                                               float);

#define INSTANTIATE_ALL_DTYPES_PCOFF(TileTag)                                     \
  INSTANTIATE_CUTE_AD_GS_PCOFF(cutlass::half_t, float, TileTag)                   \
  INSTANTIATE_CUTE_AD_GS_PCOFF(cutlass::half_t, cutlass::half_t, TileTag)         \
  INSTANTIATE_CUTE_AD_GS_PCOFF(cutlass::bfloat16_t, float, TileTag)               \
  INSTANTIATE_CUTE_AD_GS_PCOFF(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag) \
  INSTANTIATE_CUTE_TRAB_PCOFF(cutlass::half_t, float, TileTag)                    \
  INSTANTIATE_CUTE_TRAB_PCOFF(cutlass::half_t, cutlass::half_t, TileTag)          \
  INSTANTIATE_CUTE_TRAB_PCOFF(cutlass::bfloat16_t, float, TileTag)                \
  INSTANTIATE_CUTE_TRAB_PCOFF(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

// ============================================================================
// Grouped AD gather-scatter
// ============================================================================

#define INSTANTIATE_CUTE_GROUPED(ElemIn, ElemOut, TileTag)                              \
  template int run_cute_gemm_grouped_ad_gather_scatter<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                     \
      void *,                                                                           \
      const int *,                                                                      \
      const int *,                                                                      \
      const GroupedGemmParams &,                                                        \
      int,                                                                              \
      int,                                                                              \
      int,                                                                              \
      float);

#define INSTANTIATE_GROUPED_ALL_DTYPES(TileTag)                       \
  INSTANTIATE_CUTE_GROUPED(cutlass::half_t, float, TileTag)           \
  INSTANTIATE_CUTE_GROUPED(cutlass::half_t, cutlass::half_t, TileTag) \
  INSTANTIATE_CUTE_GROUPED(cutlass::bfloat16_t, float, TileTag)       \
  INSTANTIATE_CUTE_GROUPED(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

#define INSTANTIATE_CUTE_GROUPED_PCOFF(ElemIn, ElemOut, TileTag)                              \
  template int run_cute_gemm_grouped_ad_gather_scatter_pcoff<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                           \
      void *,                                                                                 \
      const int *,                                                                            \
      const int *,                                                                            \
      const GroupedGemmParams &,                                                              \
      int,                                                                                    \
      int,                                                                                    \
      int,                                                                                    \
      float);

#define INSTANTIATE_GROUPED_ALL_DTYPES_PCOFF(TileTag)                       \
  INSTANTIATE_CUTE_GROUPED_PCOFF(cutlass::half_t, float, TileTag)           \
  INSTANTIATE_CUTE_GROUPED_PCOFF(cutlass::half_t, cutlass::half_t, TileTag) \
  INSTANTIATE_CUTE_GROUPED_PCOFF(cutlass::bfloat16_t, float, TileTag)       \
  INSTANTIATE_CUTE_GROUPED_PCOFF(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

// ============================================================================
// Grouped TrAB gather
// ============================================================================

#define INSTANTIATE_CUTE_GROUPED_TRAB(ElemIn, ElemOut, TileTag)                   \
  template int run_cute_gemm_grouped_trAB_gather<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                               \
      const void *,                                                               \
      const int *,                                                                \
      const int *,                                                                \
      const GroupedTrABGemmParams &,                                              \
      int,                                                                        \
      int,                                                                        \
      float);

#define INSTANTIATE_GROUPED_TRAB_ALL_DTYPES(TileTag)                       \
  INSTANTIATE_CUTE_GROUPED_TRAB(cutlass::half_t, float, TileTag)           \
  INSTANTIATE_CUTE_GROUPED_TRAB(cutlass::half_t, cutlass::half_t, TileTag) \
  INSTANTIATE_CUTE_GROUPED_TRAB(cutlass::bfloat16_t, float, TileTag)       \
  INSTANTIATE_CUTE_GROUPED_TRAB(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

#define INSTANTIATE_CUTE_GROUPED_TRAB_PCOFF(ElemIn, ElemOut, TileTag)                   \
  template int run_cute_gemm_grouped_trAB_gather_pcoff<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                     \
      const void *,                                                                     \
      const int *,                                                                      \
      const int *,                                                                      \
      const GroupedTrABGemmParams &,                                                    \
      int,                                                                              \
      int,                                                                              \
      float);

#define INSTANTIATE_GROUPED_TRAB_ALL_DTYPES_PCOFF(TileTag)                       \
  INSTANTIATE_CUTE_GROUPED_TRAB_PCOFF(cutlass::half_t, float, TileTag)           \
  INSTANTIATE_CUTE_GROUPED_TRAB_PCOFF(cutlass::half_t, cutlass::half_t, TileTag) \
  INSTANTIATE_CUTE_GROUPED_TRAB_PCOFF(cutlass::bfloat16_t, float, TileTag)       \
  INSTANTIATE_CUTE_GROUPED_TRAB_PCOFF(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

// ============================================================================
// P5 axis-sibling macros: per-(op, backend) variant emit. Each takes
// (TileTag, LaunchSymbol). LaunchSymbol is the per-variant free-function
// name (e.g. run_cute_gemm_ad_gather_scatter_s3). Templates pending in
// warpconvnet — P6 will land template definitions for each axis.
// ============================================================================

#define INSTANTIATE_VARIANT_CUTE_SM80_AD_ONE(LaunchSymbol, ElemIn, ElemOut, TileTag) \
  template int LaunchSymbol<ElemIn, gemm::TileTag, ElemOut>(const void *,            \
                                                            const void *,            \
                                                            const void *,            \
                                                            void *,                  \
                                                            const int *,             \
                                                            const int *,             \
                                                            int,                     \
                                                            int,                     \
                                                            int,                     \
                                                            int,                     \
                                                            int,                     \
                                                            float,                   \
                                                            float);

#define INSTANTIATE_VARIANT_CUTE_SM80_AD(TileTag, LaunchSymbol)                                 \
  INSTANTIATE_VARIANT_CUTE_SM80_AD_ONE(LaunchSymbol, cutlass::half_t, float, TileTag)           \
  INSTANTIATE_VARIANT_CUTE_SM80_AD_ONE(LaunchSymbol, cutlass::half_t, cutlass::half_t, TileTag) \
  INSTANTIATE_VARIANT_CUTE_SM80_AD_ONE(LaunchSymbol, cutlass::bfloat16_t, float, TileTag)       \
  INSTANTIATE_VARIANT_CUTE_SM80_AD_ONE(                                                         \
      LaunchSymbol, cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

// TrAB shares the same template signature as AD (per kernel.h).
#define INSTANTIATE_VARIANT_CUTE_SM80_TRAB(TileTag, LaunchSymbol) \
  INSTANTIATE_VARIANT_CUTE_SM80_AD(TileTag, LaunchSymbol)

#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_AD_ONE(LaunchSymbol, ElemIn, ElemOut, TileTag) \
  template int LaunchSymbol<ElemIn, gemm::TileTag, ElemOut>(const void *,                    \
                                                            void *,                          \
                                                            const int *,                     \
                                                            const int *,                     \
                                                            const GroupedGemmParams &,       \
                                                            int,                             \
                                                            int,                             \
                                                            int,                             \
                                                            float);

#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_AD(TileTag, LaunchSymbol)                           \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_AD_ONE(LaunchSymbol, cutlass::half_t, float, TileTag)     \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_AD_ONE(                                                   \
      LaunchSymbol, cutlass::half_t, cutlass::half_t, TileTag)                                    \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_AD_ONE(LaunchSymbol, cutlass::bfloat16_t, float, TileTag) \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_AD_ONE(                                                   \
      LaunchSymbol, cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_TRAB_ONE(LaunchSymbol, ElemIn, ElemOut, TileTag) \
  template int LaunchSymbol<ElemIn, gemm::TileTag, ElemOut>(const void *,                      \
                                                            const void *,                      \
                                                            const int *,                       \
                                                            const int *,                       \
                                                            const GroupedTrABGemmParams &,     \
                                                            int,                               \
                                                            int,                               \
                                                            float);

#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_TRAB(TileTag, LaunchSymbol)                       \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_TRAB_ONE(LaunchSymbol, cutlass::half_t, float, TileTag) \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_TRAB_ONE(                                               \
      LaunchSymbol, cutlass::half_t, cutlass::half_t, TileTag)                                  \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_TRAB_ONE(                                               \
      LaunchSymbol, cutlass::bfloat16_t, float, TileTag)                                        \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM80_TRAB_ONE(                                               \
      LaunchSymbol, cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)

}  // namespace cute_gemm
}  // namespace warpconvnet
