// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.

#pragma once

#include <cuda.h>
#include <cuda_runtime.h>

#include "cute/tensor.hpp"
#include "cute_gemm_config_sm90.h"
#include "cute_gemm_kernel_sm90.h"
#include "cute_gemm_launch.h"
#include "gemm_error_codes.h"

namespace warpconvnet {
namespace cute_gemm {

// ============================================================================
// SM90 AD gather-scatter (non-grouped)
// ============================================================================

#define INSTANTIATE_SM90_AD_GS(ElemIn, ElemOut, TileTag)                                          \
  template int run_cute_gemm_sm90_ad_gather_scatter<ElemIn, gemm::TileTag, ElemOut>(const void *, \
                                                                                    const void *, \
                                                                                    const void *, \
                                                                                    void *,       \
                                                                                    const int *,  \
                                                                                    const int *,  \
                                                                                    int,          \
                                                                                    int,          \
                                                                                    int,          \
                                                                                    int,          \
                                                                                    int,          \
                                                                                    float,        \
                                                                                    float);

#define INSTANTIATE_SM90_ALL_DTYPES(TileTag)              \
  INSTANTIATE_SM90_AD_GS(cutlass::half_t, float, TileTag) \
  INSTANTIATE_SM90_AD_GS(cutlass::half_t, cutlass::half_t, TileTag)

#ifndef DISABLE_BFLOAT16
#define INSTANTIATE_SM90_ALL_DTYPES_BF16(TileTag)             \
  INSTANTIATE_SM90_AD_GS(cutlass::bfloat16_t, float, TileTag) \
  INSTANTIATE_SM90_AD_GS(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)
#else
#define INSTANTIATE_SM90_ALL_DTYPES_BF16(TileTag)
#endif

// E1 sibling: hoist gather-index __ldg out of K-loop. Templates pending.

#define INSTANTIATE_SM90_AD_GS_PCOFF(ElemIn, ElemOut, TileTag)                             \
  template int run_cute_gemm_sm90_ad_gather_scatter_pcoff<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                        \
      const void *,                                                                        \
      const void *,                                                                        \
      void *,                                                                              \
      const int *,                                                                         \
      const int *,                                                                         \
      int,                                                                                 \
      int,                                                                                 \
      int,                                                                                 \
      int,                                                                                 \
      int,                                                                                 \
      float,                                                                               \
      float);

#define INSTANTIATE_SM90_ALL_DTYPES_PCOFF(TileTag)              \
  INSTANTIATE_SM90_AD_GS_PCOFF(cutlass::half_t, float, TileTag) \
  INSTANTIATE_SM90_AD_GS_PCOFF(cutlass::half_t, cutlass::half_t, TileTag)

#ifndef DISABLE_BFLOAT16
#define INSTANTIATE_SM90_ALL_DTYPES_BF16_PCOFF(TileTag)             \
  INSTANTIATE_SM90_AD_GS_PCOFF(cutlass::bfloat16_t, float, TileTag) \
  INSTANTIATE_SM90_AD_GS_PCOFF(cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)
#else
#define INSTANTIATE_SM90_ALL_DTYPES_BF16_PCOFF(TileTag)
#endif

// ============================================================================
// SM90 grouped AD gather-scatter (staged: explicit num_stages / cp_async)
// ============================================================================

#define INSTANTIATE_SM90_STAGED_GROUPED(ElemIn, ElemOut, TileTag)                      \
  template int                                                                         \
  run_cute_gemm_grouped_ad_gather_scatter_sm90_staged<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                    \
      void *,                                                                          \
      const int *,                                                                     \
      const int *,                                                                     \
      const GroupedGemmParams &,                                                       \
      int,                                                                             \
      int,                                                                             \
      int,                                                                             \
      float,                                                                           \
      int,                                                                             \
      bool,                                                                            \
      bool);

#define INSTANTIATE_SM90_STAGED_GROUPED_PCOFF(ElemIn, ElemOut, TileTag)                      \
  template int                                                                               \
  run_cute_gemm_grouped_ad_gather_scatter_sm90_staged_pcoff<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                          \
      void *,                                                                                \
      const int *,                                                                           \
      const int *,                                                                           \
      const GroupedGemmParams &,                                                             \
      int,                                                                                   \
      int,                                                                                   \
      int,                                                                                   \
      float,                                                                                 \
      int,                                                                                   \
      bool,                                                                                  \
      bool);

// ============================================================================
// SM90 grouped AD gather-scatter (simple: tile-config defaults)
// ============================================================================

#define INSTANTIATE_SM90_GROUPED_SIMPLE(ElemIn, ElemOut, TileTag)                            \
  template int run_cute_gemm_sm90_grouped_ad_gather_scatter<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                          \
      void *,                                                                                \
      const int *,                                                                           \
      const int *,                                                                           \
      const GroupedGemmParams &,                                                             \
      int,                                                                                   \
      int,                                                                                   \
      int,                                                                                   \
      float,                                                                                 \
      bool,                                                                                  \
      bool);

#define INSTANTIATE_SM90_GROUPED_SIMPLE_PCOFF(ElemIn, ElemOut, TileTag)                            \
  template int run_cute_gemm_sm90_grouped_ad_gather_scatter_pcoff<ElemIn, gemm::TileTag, ElemOut>( \
      const void *,                                                                                \
      void *,                                                                                      \
      const int *,                                                                                 \
      const int *,                                                                                 \
      const GroupedGemmParams &,                                                                   \
      int,                                                                                         \
      int,                                                                                         \
      int,                                                                                         \
      float,                                                                                       \
      bool,                                                                                        \
      bool);

// ============================================================================
// P5 axis-sibling macros (SM90). Per-(op, backend) variant emit, takes
// (TileTag, LaunchSymbol). Templates pending in warpconvnet — P6.
// ============================================================================

#define INSTANTIATE_VARIANT_CUTE_SM90_AD_ONE(LaunchSymbol, ElemIn, ElemOut, TileTag) \
  template int LaunchSymbol<ElemIn, gemm::TileTag, ElemOut>(const void *,            \
                                                            const void *,            \
                                                            const void *,            \
                                                            void *,                  \
                                                            const int *,             \
                                                            const int *,             \
                                                            int,                     \
                                                            int,                     \
                                                            int,                     \
                                                            int,                     \
                                                            int,                     \
                                                            float,                   \
                                                            float);

#define INSTANTIATE_VARIANT_CUTE_SM90_AD(TileTag, LaunchSymbol)                                 \
  INSTANTIATE_VARIANT_CUTE_SM90_AD_ONE(LaunchSymbol, cutlass::half_t, float, TileTag)           \
  INSTANTIATE_VARIANT_CUTE_SM90_AD_ONE(LaunchSymbol, cutlass::half_t, cutlass::half_t, TileTag) \
  /* bf16 instantiations gated to match base sm90 macros. */                                    \
  INSTANTIATE_VARIANT_CUTE_SM90_AD_BF16(TileTag, LaunchSymbol)

#ifndef DISABLE_BFLOAT16
#define INSTANTIATE_VARIANT_CUTE_SM90_AD_BF16(TileTag, LaunchSymbol)                      \
  INSTANTIATE_VARIANT_CUTE_SM90_AD_ONE(LaunchSymbol, cutlass::bfloat16_t, float, TileTag) \
  INSTANTIATE_VARIANT_CUTE_SM90_AD_ONE(                                                   \
      LaunchSymbol, cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)
#else
#define INSTANTIATE_VARIANT_CUTE_SM90_AD_BF16(TileTag, LaunchSymbol)
#endif

#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_ONE(LaunchSymbol, ElemIn, ElemOut, TileTag) \
  template int LaunchSymbol<ElemIn, gemm::TileTag, ElemOut>(const void *,                    \
                                                            void *,                          \
                                                            const int *,                     \
                                                            const int *,                     \
                                                            const GroupedGemmParams &,       \
                                                            int,                             \
                                                            int,                             \
                                                            int,                             \
                                                            float,                           \
                                                            bool,                            \
                                                            bool);

#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD(TileTag, LaunchSymbol)                       \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_ONE(LaunchSymbol, cutlass::half_t, float, TileTag) \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_ONE(                                               \
      LaunchSymbol, cutlass::half_t, cutlass::half_t, TileTag)                                \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_BF16(TileTag, LaunchSymbol)

#ifndef DISABLE_BFLOAT16
#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_BF16(TileTag, LaunchSymbol)                      \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_ONE(LaunchSymbol, cutlass::bfloat16_t, float, TileTag) \
  INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_ONE(                                                   \
      LaunchSymbol, cutlass::bfloat16_t, cutlass::bfloat16_t, TileTag)
#else
#define INSTANTIATE_VARIANT_CUTE_GROUPED_SM90_AD_BF16(TileTag, LaunchSymbol)
#endif

}  // namespace cute_gemm
}  // namespace warpconvnet
