// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.

#pragma once

#include <cuda_bf16.h>
#include <cuda_fp16.h>

#include "cutlass/bfloat16.h"
#include "cutlass/half.h"

// Hand-written template body for run_implicit_wgrad / run_implicit_wgrad_grouped
// + run_implicit_gemm{,_grouped}_templated. Lives in warpconvnet/csrc/include/.
// Generated TUs need the body visible at the explicit-instantiation site.
#include "implicit_gemm_template.cuh"

namespace warpconvnet {
namespace implicit_gemm {

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_implicit_gemm_templated(const void *,
                                const void *,
                                void *,
                                const Itype *,
                                const Itype *,
                                int,
                                int,
                                int,
                                int,
                                int,
                                const std::string &,
                                int);

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_implicit_gemm_grouped_templated(const void *,
                                        const void *,
                                        void *,
                                        const Itype *,
                                        const Itype *,
                                        const Itype *,
                                        int,
                                        int,
                                        int,
                                        int,
                                        int,
                                        const std::string &,
                                        int);

}  // namespace implicit_gemm
}  // namespace warpconvnet

// Today: BlockSize + KernelVariant are runtime args; macro ignores them.
// P6: will switch to compile-time specialization.
#define INSTANTIATE_IMPLICIT_GEMM(ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant) \
  template int                                                                              \
  warpconvnet::implicit_gemm::run_implicit_gemm_templated<ElemA, ElemA, ElemOut, Itype>(    \
      const void *,                                                                         \
      const void *,                                                                         \
      void *,                                                                               \
      const Itype *,                                                                        \
      const Itype *,                                                                        \
      int,                                                                                  \
      int,                                                                                  \
      int,                                                                                  \
      int,                                                                                  \
      int,                                                                                  \
      const std::string &,                                                                  \
      int);

#define INSTANTIATE_IMPLICIT_GEMM_GROUPED(                                                       \
    ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant)                                    \
  template int                                                                                   \
  warpconvnet::implicit_gemm::run_implicit_gemm_grouped_templated<ElemA, ElemA, ElemOut, Itype>( \
      const void *,                                                                              \
      const void *,                                                                              \
      void *,                                                                                    \
      const Itype *,                                                                             \
      const Itype *,                                                                             \
      const Itype *,                                                                             \
      int,                                                                                       \
      int,                                                                                       \
      int,                                                                                       \
      int,                                                                                       \
      int,                                                                                       \
      const std::string &,                                                                       \
      int);

// ============================================================================
// Implicit wgrad — pending warpconvnet template impl. Forward decls + macros
// match the implicit_gemm shape so generated TUs compile once warpconvnet
// lands `run_implicit_wgrad*_templated` definitions.
// ============================================================================

namespace warpconvnet {
namespace implicit_wgrad {

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_implicit_wgrad_templated(const void *,
                                 const void *,
                                 void *,
                                 const Itype *,
                                 const Itype *,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 const std::string &,
                                 int);

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_implicit_wgrad_grouped_templated(const void *,
                                         const void *,
                                         void *,
                                         const Itype *,
                                         const Itype *,
                                         const Itype *,
                                         int,
                                         int,
                                         int,
                                         int,
                                         int,
                                         const std::string &,
                                         int);

}  // namespace implicit_wgrad
}  // namespace warpconvnet

#define INSTANTIATE_IMPLICIT_WGRAD(ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant) \
  template int                                                                               \
  warpconvnet::implicit_wgrad::run_implicit_wgrad_templated<ElemA, ElemA, ElemOut, Itype>(   \
      const void *,                                                                          \
      const void *,                                                                          \
      void *,                                                                                \
      const Itype *,                                                                         \
      const Itype *,                                                                         \
      int,                                                                                   \
      int,                                                                                   \
      int,                                                                                   \
      int,                                                                                   \
      int,                                                                                   \
      const std::string &,                                                                   \
      int);

#define INSTANTIATE_IMPLICIT_WGRAD_GROUPED(                                                        \
    ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant)                                      \
  template int                                                                                     \
  warpconvnet::implicit_wgrad::run_implicit_wgrad_grouped_templated<ElemA, ElemA, ElemOut, Itype>( \
      const void *,                                                                                \
      const void *,                                                                                \
      void *,                                                                                      \
      const Itype *,                                                                               \
      const Itype *,                                                                               \
      const Itype *,                                                                               \
      int,                                                                                         \
      int,                                                                                         \
      int,                                                                                         \
      int,                                                                                         \
      int,                                                                                         \
      const std::string &,                                                                         \
      int);
