// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by warpgemm.codegen.offset_gemm
// Do not edit by hand; run python -m warpgemm.codegen.

#pragma once

#include <cuda_bf16.h>
#include <cuda_fp16.h>

#include "cutlass/bfloat16.h"
#include "cutlass/half.h"

// Hand-written template body for run_split_k_implicit_gemm_templated +
// run_split_k_implicit_wgrad_templated. Lives in warpconvnet/csrc/include/.
// Generated TUs need the body visible at the explicit-instantiation site.
#include "implicit_gemm_split_k_template.cuh"

namespace warpconvnet {
namespace split_k_implicit_gemm {

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_split_k_implicit_gemm_templated(const void *,
                                        const void *,
                                        void *,
                                        const Itype *,
                                        const Itype *,
                                        int,
                                        int,
                                        int,
                                        int,
                                        int,
                                        int,
                                        void *);

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_split_k_implicit_gemm_grouped_templated(const void *,
                                                const void *,
                                                void *,
                                                const Itype *,
                                                const Itype *,
                                                const Itype *,
                                                int,
                                                int,
                                                int,
                                                int,
                                                int,
                                                int,
                                                void *);

}  // namespace split_k_implicit_gemm
}  // namespace warpconvnet

#define INSTANTIATE_IMPLICIT_GEMM_SPLIT_K(                                             \
    ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant)                          \
  template int warpconvnet::split_k_implicit_gemm::                                    \
      run_split_k_implicit_gemm_templated<ElemA, ElemA, ElemOut, Itype>(const void *,  \
                                                                        const void *,  \
                                                                        void *,        \
                                                                        const Itype *, \
                                                                        const Itype *, \
                                                                        int,           \
                                                                        int,           \
                                                                        int,           \
                                                                        int,           \
                                                                        int,           \
                                                                        int,           \
                                                                        void *);

#define INSTANTIATE_IMPLICIT_GEMM_GROUPED_SPLIT_K(                                             \
    ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant)                                  \
  template int warpconvnet::split_k_implicit_gemm::                                            \
      run_split_k_implicit_gemm_grouped_templated<ElemA, ElemA, ElemOut, Itype>(const void *,  \
                                                                                const void *,  \
                                                                                void *,        \
                                                                                const Itype *, \
                                                                                const Itype *, \
                                                                                const Itype *, \
                                                                                int,           \
                                                                                int,           \
                                                                                int,           \
                                                                                int,           \
                                                                                int,           \
                                                                                int,           \
                                                                                void *);

// ============================================================================
// Split-K implicit wgrad — templates pending in warpconvnet.
// ============================================================================

namespace warpconvnet {
namespace split_k_implicit_wgrad {

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_split_k_implicit_wgrad_templated(const void *,
                                         const void *,
                                         void *,
                                         const Itype *,
                                         const Itype *,
                                         int,
                                         int,
                                         int,
                                         int,
                                         int,
                                         int,
                                         void *);

template <typename ElementA, typename ElementB, typename ElementC, typename Itype>
int run_split_k_implicit_wgrad_grouped_templated(const void *,
                                                 const void *,
                                                 void *,
                                                 const Itype *,
                                                 const Itype *,
                                                 const Itype *,
                                                 int,
                                                 int,
                                                 int,
                                                 int,
                                                 int,
                                                 int,
                                                 void *);

}  // namespace split_k_implicit_wgrad
}  // namespace warpconvnet

#define INSTANTIATE_IMPLICIT_WGRAD_SPLIT_K(                                             \
    ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant)                           \
  template int warpconvnet::split_k_implicit_wgrad::                                    \
      run_split_k_implicit_wgrad_templated<ElemA, ElemA, ElemOut, Itype>(const void *,  \
                                                                         const void *,  \
                                                                         void *,        \
                                                                         const Itype *, \
                                                                         const Itype *, \
                                                                         int,           \
                                                                         int,           \
                                                                         int,           \
                                                                         int,           \
                                                                         int,           \
                                                                         int,           \
                                                                         void *);

#define INSTANTIATE_IMPLICIT_WGRAD_GROUPED_SPLIT_K(                                             \
    ElemA, ElemOut, ElemAcc, Itype, BlockSize, KernelVariant)                                   \
  template int warpconvnet::split_k_implicit_wgrad::                                            \
      run_split_k_implicit_wgrad_grouped_templated<ElemA, ElemA, ElemOut, Itype>(const void *,  \
                                                                                 const void *,  \
                                                                                 void *,        \
                                                                                 const Itype *, \
                                                                                 const Itype *, \
                                                                                 const Itype *, \
                                                                                 int,           \
                                                                                 int,           \
                                                                                 int,           \
                                                                                 int,           \
                                                                                 int,           \
                                                                                 int,           \
                                                                                 void *);
