# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Tile metadata adapter for the mask GEMM kernel registry.

Thin wrapper over ``warpconvnet.csrc.mask_gemm.tile_metadata`` — a
self-contained snapshot emitted by warpgemm.autotune at codegen time.
Used by ``dispatch.py`` to reason about which tile will accept a
runtime problem shape (C_in, C_out, K, groups, dtypes).

The snapshot is regenerated by setting ``WARPGEMM_REGEN=1`` during a
source build; otherwise the checked-in copy is used. Drift between the
snapshot and live warpgemm is asserted by tests/csrc/test_warpgemm_drift.py.
"""

from __future__ import annotations

from typing import Iterable

from warpconvnet.csrc.mask_gemm.tile_metadata import (
    build_tile_metadata,
    get_schema_version,
)

_MIN_SCHEMA_VERSION = 7

# Backends this build can actually launch. The sm100_umma backend is a
# compile-parseable scaffold in warpgemm with no launchable pipeline; it must
# never be selected regardless of device arch (Blackwell handoff §3).
_LAUNCHABLE_BACKENDS = frozenset({"mma_sync"})


def _device_arch_code() -> int | None:
    """Current device SM capability as major*10+minor (e.g. 89 for Ada).

    Returns ``None`` when CUDA isn't initialized — caller should skip
    arch-gate filtering in that case (CI test collection, etc.).
    """
    import torch

    if not torch.cuda.is_available():
        return None
    major, minor = torch.cuda.get_device_capability(0)
    return major * 10 + minor


# Cache arch at import — SM capability doesn't change at runtime.
_DEVICE_ARCH: int | None = None


def _get_device_arch() -> int | None:
    global _DEVICE_ARCH
    if _DEVICE_ARCH is None:
        _DEVICE_ARCH = _device_arch_code()
    return _DEVICE_ARCH


def _arch_is_binary_compatible(compiled: int, device: int) -> bool:
    """True if a cubin built for ``compiled`` executes on SM ``device``.

    CUDA's rule for non-accelerated cubins: forward compatible across minor
    revisions **within one major version**. An ``sm_100`` binary runs on
    ``sm_103``; an ``sm_90`` binary does not, and neither does ``sm_120``.
    Verified on a GB300 by launching one exact-target cubin at a time and
    reading ``cudaGetLastError()``:

        sm_100 -> ok   sm_100f -> ok   sm_103 -> ok   sm_103a -> ok
        sm_90  -> "no kernel image"    sm_120 -> "no kernel image"
        sm_100a -> "no kernel image"   (accelerated cubins are exact-match)

    Only ``mma_sync`` tiles ever reach this check (see ``_LAUNCHABLE_BACKENDS``),
    and those are compiled without an ``a`` suffix, so the non-accelerated rule
    is the applicable one.
    """
    return compiled // 10 == device // 10 and compiled % 10 <= device % 10


def _tile_arch_allowed(meta, device_arch: int) -> bool:
    """True if ``meta`` is authorized to launch on SM ``device_arch``.

    Two questions are kept apart here, because conflating them is what stranded
    every mask_gemm tile on GB300:

    1. *Can the binary execute?* — ``_arch_is_binary_compatible``, above.
    2. *Was the tile validated for this device?* — policy, below.

    A ``compile_archs`` of length 1 is an exact pin: the SM120 experimental
    family ``(120,)``, the SM100 scaffold ``(100,)``, and the SM80-only tiles
    ``(80,)`` were each certified for one architecture only. Those are never
    inherited by a family member, so ``sm_121`` still cannot launch an
    SM120-pinned experimental tile.

    A multi-entry ``compile_archs`` is the broad certified production set
    (``(80, 86, 87, 89, 90, 100, 120)``) — generic tensor-core kernels validated
    across seven architectures. Those extend to binary-compatible minor
    revisions, which is what admits GB300 (``sm_103`` via ``100``) and GB10
    (``sm_121`` via ``120``).
    """
    archs = meta.compile_archs
    if device_arch in archs:
        return True
    if len(archs) < 2:
        return False
    return any(_arch_is_binary_compatible(a, device_arch) for a in archs)


def _get_tiles(op: str, filter_arch: bool = True):
    """Return active tile records for ``op``.

    ``filter_arch=True`` (default) drops tiles the current device may not launch
    — prevents arch-pinned tiles (e.g. 10/22/24/48/49 with compile_archs=(80,))
    from appearing in dispatch candidates on Ada. See ``_tile_arch_allowed`` for
    why this is not plain membership.
    """
    if get_schema_version() < _MIN_SCHEMA_VERSION:
        raise RuntimeError(
            f"tile_metadata schema_version "
            f"{get_schema_version()} < required {_MIN_SCHEMA_VERSION}"
        )
    tiles = [
        t
        for t in build_tile_metadata(active_only=True, ops=(op,))
        if t.backend in _LAUNCHABLE_BACKENDS
    ]
    if not filter_arch:
        return tiles
    arch = _get_device_arch()
    if arch is None:
        return tiles
    return [t for t in tiles if _tile_arch_allowed(t, arch)]


# Per-op tile_id -> metadata index over the FULL registry (all tiers, all
# backends, all archs). Built lazily once; used to authorize (possibly cached
# or pinned) tile ids before they reach the C++ dispatch switch.
_METADATA_INDEX: dict[str, dict[int, object]] = {}


def _metadata_index(op: str) -> dict[int, object]:
    idx = _METADATA_INDEX.get(op)
    if idx is None:
        if get_schema_version() < _MIN_SCHEMA_VERSION:
            raise RuntimeError(
                f"tile_metadata schema_version "
                f"{get_schema_version()} < required {_MIN_SCHEMA_VERSION}"
            )
        idx = {t.tile_id: t for t in build_tile_metadata(active_only=False, ops=(op,))}
        _METADATA_INDEX[op] = idx
    return idx


def known_tile_ids(op: str) -> frozenset:
    """All tile ids present in warpgemm metadata for ``op`` (any tier/arch)."""
    return frozenset(_metadata_index(op))


def tile_launch_rejection(op: str, tile_id: int) -> str | None:
    """Reason a canonical tile id must not launch on this device, or None if OK.

    Per the Blackwell handoff §3, every candidate path is authorized here before
    entering the C++ dispatch switch — including pinned tile ids read from the
    autotune cache. Two conditions must hold: a launchable backend, and an arch
    authorization that passes ``_tile_arch_allowed``.

    The arch check is binary compatibility within a major version (never a bare
    ``>=`` over arch codes, which would wrongly admit an sm_90 tile on sm_100),
    and single-arch pins remain exact so an experimental tile is never inherited
    by a newer device code. See ``_tile_arch_allowed``.

    Ids absent from warpgemm metadata (warpconvnet-only carve-outs such as the
    scalar/f32-out fallbacks) are the CALLER's responsibility to allowlist —
    this function returns a rejection for unknown ids so foreign/stale cached
    ids cannot slip through as "not in metadata, assume fine".
    """
    meta = _metadata_index(op).get(tile_id)
    if meta is None:
        return f"tile {tile_id} not present in warpgemm {op} metadata"
    if meta.backend not in _LAUNCHABLE_BACKENDS:
        return f"tile {tile_id} backend={meta.backend!r} is not launchable in this build"
    arch = _get_device_arch()
    if arch is not None and not _tile_arch_allowed(meta, arch):
        return (
            f"tile {tile_id} compile_archs={meta.compile_archs} excludes " f"device arch sm_{arch}"
        )
    return None


# ---------------------------------------------------------------------------
# Filter + rank (same shape as warpgemm's tile_metadata_example.py)
# ---------------------------------------------------------------------------


def candidate_tiles(
    op: str,
    C_in: int,
    C_out: int,
    K: int,
    groups: int = 1,
    input_dtype: str = "f16",
    output_dtype: str = "f16",
    tier: str = "production",
    acc_dtype: str | None = None,
) -> list:
    """Return tiles that will accept the runtime shape (correctness gate).

    Uses warpgemm's v4 ``TileMetadata.accepts(...)`` when ``acc_dtype`` is
    set; otherwise composes the pre-v4 helpers so callers that don't care
    about accumulator can still filter.
    """
    mw_needed = (K + 31) // 32
    tiles = _get_tiles(op)
    acc = acc_dtype or "f32"
    return [
        m
        for m in tiles
        if m.tier == tier and m.accepts(C_in, C_out, K, groups, input_dtype, output_dtype, acc)
    ]


def rank_candidates(
    candidates: Iterable,
    C_in: int,
    C_out: int,
    groups: int = 1,
    prefer_fp16_accum: bool = False,
) -> list:
    """Rank candidates by perf preference. Best first."""
    pref_acc = "f16" if prefer_fp16_accum else "f32"

    def key(m):
        return (
            not m.prefers_vectorized_c_in(C_in, groups),
            not m.prefers_vectorized_c_out(C_out, groups),
            m.acc_dtype != pref_acc,
            -(m.tile_m * m.tile_n),
            m.tile_id,
        )

    return sorted(candidates, key=key)


def pick_tile(
    op: str,
    C_in: int,
    C_out: int,
    K: int,
    groups: int = 1,
    input_dtype: str = "f16",
    output_dtype: str = "f16",
    prefer_fp16_accum: bool = False,
    acc_dtype: str | None = None,
) -> object | None:
    """Filter + rank + top candidate. None if no tile fits.

    ``acc_dtype`` (``"f16"`` or ``"f32"``) hard-filters on accumulator; when
    unset, ``prefer_fp16_accum`` biases the ranker instead.
    """
    c = candidate_tiles(op, C_in, C_out, K, groups, input_dtype, output_dtype, acc_dtype=acc_dtype)
    if not c:
        return None
    return rank_candidates(c, C_in, C_out, groups, prefer_fp16_accum)[0]


def explain(
    op: str,
    C_in: int,
    C_out: int,
    K: int,
    groups: int = 1,
    input_dtype: str = "f16",
    output_dtype: str = "f16",
    acc_dtype: str | None = None,
) -> str:
    """Human-readable diagnostic for a dispatch lookup."""
    mw_needed = (K + 31) // 32
    tiles = _get_tiles(op)
    out = [
        f"Problem: op={op} C_in={C_in} C_out={C_out} K={K} "
        f"groups={groups} dtypes={input_dtype}->{output_dtype}",
        f"Active {op} tiles: {len(tiles)}",
    ]

    survivors = []
    for t in tiles:
        if t.tier != "production":
            out.append(f"  reject tile {t.tile_id:>3}: tier={t.tier}")
            continue
        if not t.supports_mask_words(mw_needed):
            out.append(f"  reject tile {t.tile_id:>3}: mask_words={t.mask_words} < {mw_needed}")
            continue
        if not t.handles_c_in(C_in, groups):
            out.append(
                f"  reject tile {t.tile_id:>3}: C_in={C_in}/g={groups} fails "
                f"padded >= {t.min_per_group_c_in}"
            )
            continue
        if not t.handles_c_out(C_out, groups):
            out.append(
                f"  reject tile {t.tile_id:>3}: C_out={C_out}/g={groups} fails "
                f"padded >= {t.min_per_group_c_out}"
            )
            continue
        if not t.handles_dtypes(input_dtype, output_dtype):
            out.append(
                f"  reject tile {t.tile_id:>3}: dtypes {input_dtype}->{output_dtype} "
                f"not in {t.supported_input_dtypes}->{t.supported_output_dtypes}"
            )
            continue
        if acc_dtype is not None and not t.handles_accumulator(acc_dtype):
            out.append(
                f"  reject tile {t.tile_id:>3}: acc={acc_dtype} "
                f"not in {t.supported_accumulator_dtypes}"
            )
            continue
        survivors.append(t)

    out.append(f"Survivors: {len(survivors)}")
    ranked = rank_candidates(survivors, C_in, C_out, groups)
    for i, t in enumerate(ranked[:5]):
        vec_in = t.prefers_vectorized_c_in(C_in, groups)
        vec_out = t.prefers_vectorized_c_out(C_out, groups)
        out.append(
            f"  [{i}] tile {t.tile_id:>3} {t.kernel_struct}  "
            f"mnk=({t.tile_m},{t.tile_n},{t.tile_k})  acc={t.acc_dtype}  "
            f"vec_in={vec_in} vec_out={vec_out}"
        )
    return "\n".join(out)
