// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by warpgemm.codegen.generate_dgrad.compose_dgrad_helpers_iter_fragment().
// DO NOT EDIT — changes will be overwritten on next codegen run.
//
// Struct-body fragment for MaskGemm_dgrad_* tiles that match
// _uses_iter_helpers(cfg). #include'd inside private: of those tiles.
// References outer-struct constants (tM, tN, tK, kVec, MaskWords,
// ElementInput, ElementOutput, GmemTiledCopyB, UseSmemEpilogue,
// SplitOffsets) and SharedStorage layout (real_rows, row_masks).

#include "warpgemm_a_loader_iter.cuh"

static constexpr bool BIsTransposed = true;

// _load_B_tile: K-contiguous B load for dgrad.
//
// INTEGRATOR CONTRACT — B layout for dgrad
// ----------------------------------------
// Despite the name "B is transposed" (BIsTransposed = true above), the
// weight tensor must be passed UN-TRANSPOSED in its native layout
//
//     weight: [K, G, C_in, C_out]   row-major
//
// i.e. each per-K plane is a [C_in, C_out] matrix (rows of length C_out
// indexed by C_in). Do NOT call weight.transpose(1, 2) before launch.
//
// The address arithmetic below — gmem_row_base + (n_start + n_local) *
// K_dim — walks rows of length K_dim with K_dim = C_out. Concretely it
// reads B[n_local, k_local] = weight[k_offset, c_in=n_local, c_out=k_local],
// which is what the GEMM accum[in_idx, c_in] += A[in_idx, c_out] *
// B[c_out_axis, c_in_axis] needs (with the K axis = C_out and the N axis
// = C_in, which is dgrad's per-tile MMA convention).
//
// Passing transposed weight gives output of the right magnitude but with
// ~zero correlation to the true gradient (rdiff ~1.4 in practice). This
// bug broke ScanNet training in warpconvnet — see warpconvnet commit
// 0e98dd7d and notes/2026_04_17_DGRAD_NUMERICAL_BUG.md.
//
// Optimized: precompute smem base address once, use compile-time offsets
// for each wave to minimize instruction count.
template <class SmemTensor, class GmemThrCopyB>
__device__ void _load_B_tile(const ElementInput *ptr_Bk,
                             SmemTensor smem_stage,
                             GmemThrCopyB & /*unused*/,
                             int n_start,
                             int k_start,
                             int N_dim,
                             int K_dim,
                             bool n_full_tile) const {
  static_assert(tK % kVec == 0);
  constexpr int k_vecs = tK / kVec;
  constexpr int k_threads = k_vecs;
  constexpr int n_per_wave = MaxThreadsPerBlock / k_threads;
  constexpr int num_waves = (tN + n_per_wave - 1) / n_per_wave;

  // Precompute this thread's K-position and N-position within wave
  int k_tid = threadIdx.x % k_threads;
  int n_tid = threadIdx.x / k_threads;
  int k_local = k_tid * kVec;
  int k_global = k_start + k_local;
  // Partial K: compute valid bytes for cp.async (handles non-kVec-aligned K_dim)
  int k_valid_n = (k_global < K_dim) ? min(kVec, K_dim - k_global) : 0;
  int k_src_bytes = k_valid_n * (int)sizeof(ElementInput);
  bool k_full = (k_valid_n == kVec);

  // Precompute gmem base for this thread
  const ElementInput *gmem_row_base = ptr_Bk + k_global;  // + n * K_dim per row
  // Group-conv alignment: cp.async.v4 needs 16-byte source. Misaligned when
  // ptr_Bk or K_dim * sizeof(half) isn't 16-byte aligned (groups>1 with
  // per-group C_out not multiple of kVec).
  bool b_aligned =
      ((reinterpret_cast<uintptr_t>(ptr_Bk) | (uintptr_t)(K_dim * (int)sizeof(ElementInput))) &
       15u) == 0;

  if (n_full_tile && k_full && b_aligned) {
    // Fast path: no bounds checking, all waves valid
    CUTLASS_PRAGMA_UNROLL
    for (int wave = 0; wave < num_waves; ++wave) {
      int n_local = wave * n_per_wave + n_tid;
      uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_stage(n_local, k_local));
      const void *src = gmem_row_base + (int64_t)(n_start + n_local) * K_dim;
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(smem_addr),
                   "l"(src),
                   "n"(16));
    }
  } else {
    // Partial tile: fall back to per-element scalar load + st.shared.v4.b32.
    //
    // Why NOT partial cp.async (earlier buggy implementation):
    //   cp.async with cp-size=16 requires a 16-byte-aligned source even when
    //   src-size<16. For dgrad B with K_dim=C_out not a multiple of kVec=8,
    //   the source address `ptr_Bk + n_global * K_dim` is only 2*K_dim-byte
    //   aligned. For odd n_global at small C_out (3,4,5,7) this is <8-byte
    //   aligned → unaligned cp.async yields garbage / replicated data for
    //   odd n-rows. Observed as silent corruption at the last C_in column
    //   (only the c_in=63 slot failed; odd c_in positions silently dropped
    //   their weight contribution and spilled into adjacent even c_in).
    //   See notes/2026_04_17_codegen_drift_audit.md for the analogue on the
    //   A-loader side.
    //
    // Scalar fallback: per-element ld.global (no alignment requirement),
    // pack into int4 register, then st.shared.v4.b32. Same pattern used by
    // gathered_a_warp_raked / gathered_a_precomputed / gathered_a_iterator.
    CUTLASS_PRAGMA_UNROLL
    for (int wave = 0; wave < num_waves; ++wave) {
      int n_local = wave * n_per_wave + n_tid;
      if (n_local < tN) {
        int n_global = n_start + n_local;
        uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_stage(n_local, k_local));
        int4 frag = make_int4(0, 0, 0, 0);
        if (n_global < N_dim && k_valid_n > 0) {
          const ElementInput *row_ptr = ptr_Bk + (int64_t)n_global * K_dim;
          ElementInput *dst = reinterpret_cast<ElementInput *>(&frag);
          CUTLASS_PRAGMA_UNROLL
          for (int v = 0; v < kVec; ++v) {
            int k = k_global + v;
            if (k < K_dim) dst[v] = row_ptr[k];
          }
        }
        asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                     "r"(frag.x),
                     "r"(frag.y),
                     "r"(frag.z),
                     "r"(frag.w));
      }
    }
  }
}

// Legacy transposed API (backward compat)
template <class SmemTensor>
__device__ void _load_B_tile_transposed(const ElementInput *ptr_Bk,
                                        SmemTensor smem_stage,
                                        int n_start,
                                        int k_start,
                                        int N_dim,
                                        int K_dim) const {
  _load_dense_B_generic<SmemTensor, true>(ptr_Bk, smem_stage, n_start, k_start, N_dim, K_dim);
}

/// Unified dense B load via cp.async, parameterized by layout.
template <class SmemTensor, bool IsTransposed>
__device__ void _load_dense_B_generic(const ElementInput *ptr_B,
                                      SmemTensor smem_tile,
                                      int n_start,
                                      int k_start,
                                      int N,
                                      int K_dim) const {
  static_assert(tN % kVec == 0);
  static_assert(tK % kVec == 0);
  constexpr int n_vecs = tN / kVec;
  constexpr int k_vecs = tK / kVec;
  // For N-contiguous: cp.async loads kVec elements along N. Iterate all K rows × N vectors.
  // For K-contiguous: cp.async loads kVec elements along K. Iterate all N rows × K vectors.
  constexpr int total_vecs = IsTransposed ? (tN * k_vecs) : (tK * n_vecs);
  // 128-bit cp.async needs a 16B-aligned source even when src_bytes<16. A
  // sub-16B weight base (DeepSpeed ZeRO contiguous-view weights) faults
  // "misaligned address". Guard on (base | stride*sizeof); scalar fallback
  // when misaligned. Stride: N (fwd, N-contig) / K_dim (transposed).
  int _b_stride_bytes = (IsTransposed ? K_dim : N) * (int)sizeof(ElementInput);
  bool b_aligned = ((reinterpret_cast<uintptr_t>(ptr_B) | (uintptr_t)_b_stride_bytes) & 15u) == 0;
  CUTLASS_PRAGMA_UNROLL
  for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
    int k_local, n_local;
    if constexpr (!IsTransposed) {
      // Forward (N-contiguous): K outer (step=1), N-vec inner (step=kVec)
      k_local = idx / n_vecs;
      n_local = (idx % n_vecs) * kVec;
    } else {
      // Transposed (K-contiguous): N outer (step=1), K-vec inner (step=kVec)
      n_local = idx / k_vecs;
      k_local = (idx % k_vecs) * kVec;
    }
    int n_global = n_start + n_local;
    int k_global = k_start + k_local;
    uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
    const void *src;
    int src_bytes;
    if constexpr (!IsTransposed) {
      // N-contiguous: vector along N, partial at N boundary
      int valid_n = (k_global < K_dim && n_global < N) ? min(kVec, N - n_global) : 0;
      src_bytes = valid_n * (int)sizeof(ElementInput);
      src = &ptr_B[k_global * N + n_global];
    } else {
      // K-contiguous: vector along K, partial at K boundary
      int valid_k = (n_global < N && k_global < K_dim) ? min(kVec, K_dim - k_global) : 0;
      src_bytes = valid_k * (int)sizeof(ElementInput);
      src = &ptr_B[n_global * K_dim + k_global];
    }
    if (src_bytes > 0 && b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                   "l"(src),
                   "n"(16),
                   "r"(src_bytes));
    } else if (b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                   "l"(ptr_B),
                   "n"(16),
                   "r"(0));
    } else {
      int4 frag = make_int4(0, 0, 0, 0);
      if (src_bytes > 0) {
        const ElementInput *s = reinterpret_cast<const ElementInput *>(src);
        ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
        int nvalid = src_bytes / (int)sizeof(ElementInput);
        CUTLASS_PRAGMA_UNROLL
        for (int e = 0; e < kVec; ++e)
          if (e < nvalid) d[e] = s[e];
      }
      asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                   "r"(frag.x),
                   "r"(frag.y),
                   "r"(frag.z),
                   "r"(frag.w));
    }
  }
}

/// Unified per-kblock B load for fused mainloop interleaving.
/// Warp-raked for both N-contiguous and K-contiguous cases.
template <class SmemTensor, int KB, bool IsTransposed = BIsTransposed>
__device__ void _load_B_kblock(const ElementInput *ptr_B,
                               SmemTensor smem_tile,
                               int n_start,
                               int k_start,
                               int N,
                               int K_dim) const {
  static_assert(tN % kVec == 0);
  constexpr int k_offset = KB * kMmaK;

  // 128-bit cp.async requires a 16B-aligned source even when src_bytes<16.
  // A sub-16B weight base (DeepSpeed ZeRO contiguous-view weights) faults
  // "misaligned address". Guard the cp.async path on (base | stride*sizeof);
  // fall back to per-element scalar load + st.shared.v4 when misaligned.
  // Stride between contiguous rows: N (fwd, N-contig) / K_dim (transposed).
  int _b_stride_bytes = (IsTransposed ? K_dim : N) * (int)sizeof(ElementInput);
  bool b_aligned = ((reinterpret_cast<uintptr_t>(ptr_B) | (uintptr_t)_b_stride_bytes) & 15u) == 0;

  if constexpr (!IsTransposed) {
    // Forward (N-contiguous): each cp.async loads kVec N-elements at 1 K-row.
    // Warp-raked: K outer (step=1), N-vec inner (step=kVec).
    constexpr int n_vecs = tN / kVec;
    constexpr int total_vecs = kMmaK * n_vecs;
    CUTLASS_PRAGMA_UNROLL
    for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
      int k_local = k_offset + idx / n_vecs;
      int n_local = (idx % n_vecs) * kVec;
      int n_global = n_start + n_local;
      int k_global = k_start + k_local;
      uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
      int valid_n = (k_global < K_dim && n_global < N) ? min(kVec, N - n_global) : 0;
      int src_bytes = valid_n * (int)sizeof(ElementInput);
      if (src_bytes > 0 && b_aligned) {
        const void *src = &ptr_B[k_global * N + n_global];
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                     "l"(src),
                     "n"(16),
                     "r"(src_bytes));
      } else if (b_aligned) {
        asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                     "l"(ptr_B),
                     "n"(16),
                     "r"(0));
      } else {
        int4 frag = make_int4(0, 0, 0, 0);
        if (src_bytes > 0) {
          const ElementInput *s = &ptr_B[k_global * N + n_global];
          ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
          CUTLASS_PRAGMA_UNROLL
          for (int e = 0; e < kVec; ++e)
            if (n_global + e < N) d[e] = s[e];
        }
        asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                     "r"(frag.x),
                     "r"(frag.y),
                     "r"(frag.z),
                     "r"(frag.w));
      }
    }
  } else {
    // Transposed (K-contiguous): each cp.async loads kVec K-elements at 1 N-row.
    // Warp-raked: threads in a warp cover consecutive K-vectors at same N-row.
    constexpr int k_vecs_per_block = kMmaK / kVec;
    constexpr int k_threads = k_vecs_per_block;  // threads per N-row along K
    constexpr int n_per_wave = MaxThreadsPerBlock / k_threads;
    constexpr int num_waves = (tN + n_per_wave - 1) / n_per_wave;

    int k_tid = threadIdx.x % k_threads;
    int n_tid = threadIdx.x / k_threads;

    CUTLASS_PRAGMA_UNROLL
    for (int wave = 0; wave < num_waves; ++wave) {
      int n_local = wave * n_per_wave + n_tid;
      int k_local = k_offset + k_tid * kVec;
      int n_global = n_start + n_local;
      int k_global = k_start + k_local;
      if (n_local < tN) {
        uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
        int valid_k = (n_global < N && k_global < K_dim) ? min(kVec, K_dim - k_global) : 0;
        int src_bytes = valid_k * (int)sizeof(ElementInput);
        if (src_bytes > 0 && b_aligned) {
          const void *src = &ptr_B[n_global * K_dim + k_global];
          asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                       "l"(src),
                       "n"(16),
                       "r"(src_bytes));
        } else if (b_aligned) {
          asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                       "l"(ptr_B),
                       "n"(16),
                       "r"(0));
        } else {
          int4 frag = make_int4(0, 0, 0, 0);
          if (src_bytes > 0) {
            const ElementInput *s = &ptr_B[n_global * K_dim + k_global];
            ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
            CUTLASS_PRAGMA_UNROLL
            for (int e = 0; e < kVec; ++e)
              if (k_global + e < K_dim) d[e] = s[e];
          }
          asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                       "r"(frag.x),
                       "r"(frag.y),
                       "r"(frag.z),
                       "r"(frag.w));
        }
      }
    }
  }
}

// Legacy generic per-kblock B load (round-robin, non-raked — kept for reference).
template <class SmemTensor, int KB, bool IsTransposed_unused = BIsTransposed>
__device__ void _load_B_kblock_generic(const ElementInput *ptr_B,
                                       SmemTensor smem_tile,
                                       int n_start,
                                       int k_start,
                                       int N,
                                       int K_dim) const {
  static_assert(tN % kVec == 0);
  constexpr int n_vecs = tN / kVec;
  constexpr int k_offset = KB * kMmaK;
  constexpr int k_vecs = kMmaK / kVec;
  constexpr int total_vecs = IsTransposed_unused ? (tN * k_vecs) : (kMmaK * n_vecs);
  // Guard 128-bit cp.async on a 16B-aligned weight base (DeepSpeed ZeRO
  // contiguous-view weights are sub-16B → "misaligned address"). Stride:
  // N (fwd, N-contig) / K_dim (transposed). Scalar fallback when misaligned.
  int _b_stride_bytes = (IsTransposed_unused ? K_dim : N) * (int)sizeof(ElementInput);
  bool b_aligned = ((reinterpret_cast<uintptr_t>(ptr_B) | (uintptr_t)_b_stride_bytes) & 15u) == 0;

  CUTLASS_PRAGMA_UNROLL
  for (int idx = threadIdx.x; idx < total_vecs; idx += MaxThreadsPerBlock) {
    int k_local, n_local;
    if constexpr (!IsTransposed_unused) {
      k_local = k_offset + idx / n_vecs;
      n_local = (idx % n_vecs) * kVec;
    } else {
      n_local = idx / k_vecs;
      k_local = k_offset + (idx % k_vecs) * kVec;
    }
    int n_global = n_start + n_local;
    int k_global = k_start + k_local;
    uint32_t smem_addr = cute::cast_smem_ptr_to_uint(&smem_tile(n_local, k_local));
    bool pred;
    const void *src;
    if constexpr (!IsTransposed_unused) {
      pred = (k_global < K_dim) && (n_global + kVec <= N);
      src = &ptr_B[k_global * N + n_global];
    } else {
      pred = (n_global < N) && (k_global + kVec <= K_dim);
      src = &ptr_B[n_global * K_dim + k_global];
    }
    if (pred && b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(smem_addr),
                   "l"(src),
                   "n"(16));
    } else if (b_aligned) {
      asm volatile("cp.async.ca.shared.global.L2::128B [%0], [%1], %2, %3;\n" ::"r"(smem_addr),
                   "l"(ptr_B),
                   "n"(16),
                   "r"(0));
    } else {
      int4 frag = make_int4(0, 0, 0, 0);
      if (pred) {
        const ElementInput *s = reinterpret_cast<const ElementInput *>(src);
        ElementInput *d = reinterpret_cast<ElementInput *>(&frag);
        CUTLASS_PRAGMA_UNROLL
        for (int e = 0; e < kVec; ++e) d[e] = s[e];
      }
      asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(smem_addr),
                   "r"(frag.x),
                   "r"(frag.y),
                   "r"(frag.z),
                   "r"(frag.w));
    }
  }
}

template <class Accumulator, class TiledMma_>
__device__ void _epilogue_direct(Accumulator &accum,
                                 ElementOutput *ptr_D,
                                 const int *mask_argsort,
                                 int m_start,
                                 int n_start,
                                 int N_in,
                                 int C_in,
                                 float alpha,
                                 TiledMma_ &tiled_mma,
                                 char *smem_buf,
                                 int stride_out = 0) const {
  if (stride_out == 0) stride_out = C_in;
  using namespace cute;
  auto thr_mma = tiled_mma.get_slice(threadIdx.x);
  Tensor tCrC = thr_mma.partition_C(make_identity_tensor(make_shape(Int<tM>{}, Int<tN>{})));

  if constexpr (sizeof(ElementOutput) == 2 && UseSmemEpilogue) {
    // Shared memory staging epilogue (CUTLASS pattern)
    constexpr int EPL_PAD = 8;
    constexpr int EPL_STRIDE = tN + EPL_PAD;
    // Stage in ElementOutput (half_t OR bfloat16_t), not __half — otherwise
    // bf16 output gets fp16 bits and the uint64 packed stores emit garbage.
    ElementOutput *epi_smem = reinterpret_cast<ElementOutput *>(smem_buf);

    CUTE_UNROLL
    for (int i = 0; i < size(accum); ++i) {
      auto coord = tCrC(i);
      float val = (alpha == 1.0f) ? float(accum(i)) : alpha * float(accum(i));
      epi_smem[get<0>(coord) * EPL_STRIDE + get<1>(coord)] = static_cast<ElementOutput>(val);
    }
    __syncthreads();

    constexpr int VEC = 4;
    constexpr int COLS_PER_THREAD = tN / VEC;
    constexpr int ROWS_PER_ITER = MaxThreadsPerBlock / COLS_PER_THREAD;
    int col_group = threadIdx.x % COLS_PER_THREAD;
    int row_in_iter = threadIdx.x / COLS_PER_THREAD;
    int col_start = col_group * VEC;

    // Group-conv alignment: uint64 stores need 8-byte alignment of the
    // target. ptr_D = ptr_D_base + group_id * C_per_group; if that shift
    // (plus stride_out*2) isn't 8-byte aligned, uint64 stores misalign.
    // Fall back to scalar writes in that case.
    bool epi_aligned = ((reinterpret_cast<uintptr_t>(ptr_D) |
                         (uintptr_t)(stride_out * (int)sizeof(ElementOutput))) &
                        7u) == 0;

#pragma unroll
    for (int iter = 0; iter < tM; iter += ROWS_PER_ITER) {
      int row = iter + row_in_iter;
      if (row < tM) {
        int sorted_row = m_start + row;
        if (sorted_row < N_in && col_start + n_start + VEC <= C_in && epi_aligned) {
          int out_row = mask_argsort[sorted_row];
          uint64_t packed;
          memcpy(&packed, &epi_smem[row * EPL_STRIDE + col_start], sizeof(uint64_t));
          char *dst = reinterpret_cast<char *>(ptr_D) +
                      ((size_t)out_row * stride_out + n_start + col_start) * 2;
          *reinterpret_cast<uint64_t *>(dst) = packed;
        } else if (sorted_row < N_in) {
          int out_row = mask_argsort[sorted_row];
          for (int v = 0; v < VEC; ++v) {
            int n_global = n_start + col_start + v;
            if (n_global < C_in) {
              ElementOutput h = epi_smem[row * EPL_STRIDE + col_start + v];
              memcpy(&ptr_D[out_row * stride_out + n_global], &h, 2);
            }
          }
        }
      }
    }
  } else if constexpr (sizeof(ElementOutput) == 2) {
    // Direct half2 epilogue (no smem staging — lower overhead for small tiles).
    // Half2 stores require 4-byte alignment: ptr_D (after per-group shift),
    // the column index (n_global), and the row stride (stride_out) must all
    // yield 4-byte-aligned target addresses.
    bool ptr_D_aligned = (reinterpret_cast<uintptr_t>(ptr_D) & 3u) == 0;
    bool stride_aligned = (stride_out & 1) == 0;
    CUTE_UNROLL
    for (int frag = 0; frag < size(accum); frag += 4) {
#pragma unroll
      for (int pair = 0; pair < 2; ++pair) {
        int base = frag + pair * 2;
        auto coord = tCrC(base);
        int sorted_row = m_start + get<0>(coord);
        int n_global = n_start + get<1>(coord);
        if (sorted_row < N_in && n_global + 1 < C_in && stride_aligned && ptr_D_aligned &&
            ((n_global & 1) == 0)) {
          int out_row = mask_argsort[sorted_row];
          float v0 = (alpha == 1.0f) ? float(accum(base)) : alpha * float(accum(base));
          float v1 = (alpha == 1.0f) ? float(accum(base + 1)) : alpha * float(accum(base + 1));
          // dtype-generic pack (half_t OR bfloat16_t); __float2half would
          // corrupt bf16 output. static_cast rounds float->ElementOutput.
          ElementOutput e0 = static_cast<ElementOutput>(v0), e1 = static_cast<ElementOutput>(v1);
          unsigned short s0, s1;
          memcpy(&s0, &e0, 2);
          memcpy(&s1, &e1, 2);
          uint32_t packed = (uint32_t)s0 | ((uint32_t)s1 << 16);
          char *base_ptr = reinterpret_cast<char *>(ptr_D);
          *reinterpret_cast<uint32_t *>(base_ptr + ((size_t)out_row * stride_out + n_global) * 2) =
              packed;
        } else if (sorted_row < N_in) {
          // Scalar fallback: either the write would straddle C (n_global+1 >= C)
          // or the half2 store would be misaligned (stride or col odd).
          int out_row = mask_argsort[sorted_row];
          if (n_global < C_in) {
            float val = (alpha == 1.0f) ? float(accum(base)) : alpha * float(accum(base));
            ptr_D[out_row * stride_out + n_global] = static_cast<ElementOutput>(val);
          }
          if (n_global + 1 < C_in) {
            float val1 = (alpha == 1.0f) ? float(accum(base + 1)) : alpha * float(accum(base + 1));
            ptr_D[out_row * stride_out + n_global + 1] = static_cast<ElementOutput>(val1);
          }
        }
      }
    }
  } else {
    // f32 output path: scalar stores
    CUTE_UNROLL
    for (int i = 0; i < size(accum); ++i) {
      auto coord = tCrC(i);
      int sorted_row = m_start + get<0>(coord);
      int n_global = n_start + get<1>(coord);
      if (sorted_row < N_in && n_global < C_in) {
        int out_row = mask_argsort[sorted_row];
        float val = float(accum(i));
        ElementOutput result = (alpha == 1.0f) ? static_cast<ElementOutput>(val)
                                               : static_cast<ElementOutput>(alpha * val);
        ptr_D[out_row * stride_out + n_global] = result;
      }
    }
  }
}

template <class Accumulator, class TiledMma_>
__device__ void _epilogue_atomic(Accumulator &accum,
                                 ElementOutput *ptr_D,
                                 const int *mask_argsort,
                                 int m_start,
                                 int n_start,
                                 int N_in,
                                 int C_in,
                                 float alpha,
                                 TiledMma_ &tiled_mma,
                                 int stride_out = 0) const {
  if (stride_out == 0) stride_out = C_in;
  using namespace cute;
  auto thr_mma = tiled_mma.get_slice(threadIdx.x);
  Tensor tCrC = thr_mma.partition_C(make_identity_tensor(make_shape(Int<tM>{}, Int<tN>{})));

  // Atomic epilogue: each element uses atomicAdd to accumulate across Y-blocks.
  // For fp16 output, use atomicAdd(__half*, __half) which is supported on SM70+.
  CUTE_UNROLL
  for (int i = 0; i < size(accum); ++i) {
    auto coord = tCrC(i);
    int sorted_row = m_start + get<0>(coord);
    int n_global = n_start + get<1>(coord);
    if (sorted_row < N_in && n_global < C_in) {
      int out_row = mask_argsort[sorted_row];
      float val = (alpha == 1.0f) ? float(accum(i)) : alpha * float(accum(i));
      if constexpr (cute::is_same<ElementOutput, cutlass::half_t>::value) {
        atomicAdd(reinterpret_cast<__half *>(ptr_D + out_row * stride_out + n_global),
                  __float2half(val));
      } else if constexpr (cute::is_same<ElementOutput, cutlass::bfloat16_t>::value) {
        // bf16 atomicAdd (SM80+); __float2half would corrupt the bf16 target.
        atomicAdd(reinterpret_cast<__nv_bfloat16 *>(ptr_D + out_row * stride_out + n_global),
                  __float2bfloat16(val));
      } else {
        atomicAdd(ptr_D + out_row * stride_out + n_global, static_cast<ElementOutput>(val));
      }
    }
  }
}

template <class Accumulator, class TiledMma_>
__device__ void _epilogue_scalar(Accumulator &accum,
                                 ElementOutput *ptr_D,
                                 const int *mask_argsort,
                                 int m_start,
                                 int n_start,
                                 int N_in,
                                 int C_in,
                                 float alpha,
                                 TiledMma_ &tiled_mma,
                                 int stride_out = 0) const {
  if (stride_out == 0) stride_out = C_in;
  using namespace cute;
  auto thr_mma = tiled_mma.get_slice(threadIdx.x);
  Tensor tCrC = thr_mma.partition_C(make_identity_tensor(make_shape(Int<tM>{}, Int<tN>{})));

  // Scalar epilogue: write one element at a time (no alignment requirement)
  CUTE_UNROLL
  for (int i = 0; i < size(accum); ++i) {
    auto coord = tCrC(i);
    int sorted_row = m_start + get<0>(coord);
    int n_global = n_start + get<1>(coord);
    if (sorted_row < N_in && n_global < C_in) {
      int out_row = mask_argsort[sorted_row];
      float val = (alpha == 1.0f) ? float(accum(i)) : alpha * float(accum(i));
      ptr_D[out_row * stride_out + n_global] = static_cast<ElementOutput>(val);
    }
  }
}
