// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by warpgemm.codegen.generate.compose_a_loader_precomputed_fragment().
// DO NOT EDIT — changes will be overwritten on next codegen run.
//
// Cross-kernel A-loader fragment shared by fwd + dgrad helper fragments.
// Struct-body fragment, transitively #include'd inside per-tile struct private:.

// ---- Pre-computed A loader (bypasses CuTe in hot path) ----

static constexpr int k_vecs_A = tK / kVec;
static constexpr int total_vecs_A = tM * k_vecs_A;
static constexpr int kItersPerThread = (total_vecs_A + MaxThreadsPerBlock - 1) / MaxThreadsPerBlock;

struct AIteratorState {
  int gmem_byte_offsets[kItersPerThread];  // in_row * C * sizeof(half), per K-offset
  bool valid[kItersPerThread];             // per K-offset
  // Pre-computed per-thread constants (set once, reused across all offsets + k-tiles):
  int m_local[kItersPerThread];        // M-row for each iteration
  int k_byte_offset[kItersPerThread];  // k_local * sizeof(half)
  // Cached from smem (read once in init, avoid repeated LDS per offset):
  int cached_real_row[kItersPerThread];       // from storage.real_rows[m]
  uint32_t cached_row_mask[kItersPerThread];  // from storage.row_masks[m]
};

/// Pre-compute thread's iteration constants + cache smem row info.
/// Called ONCE after mask_union populates storage.real_rows/row_masks.
/// Caches real_row and row_mask in registers to avoid LDS per offset.
__device__ void _init_A_iterator(AIteratorState &state,
                                 const int *real_rows,
                                 const uint32_t *row_masks) const {
  CUTLASS_PRAGMA_UNROLL
  for (int r = 0; r < kItersPerThread; ++r) {
    int vec_idx = threadIdx.x + r * MaxThreadsPerBlock;
    if (vec_idx < total_vecs_A) {
      int m = vec_idx / k_vecs_A;
      state.m_local[r] = m;
      state.k_byte_offset[r] = (vec_idx % k_vecs_A) * kVec * sizeof(ElementInput);
      // Cache smem reads in registers (avoid LDS per offset iteration)
      if (m < tM) {
        state.cached_real_row[r] = real_rows[m];
        state.cached_row_mask[r] = row_masks[m];
      } else {
        state.cached_real_row[r] = -1;
        state.cached_row_mask[r] = 0;
      }
    } else {
      state.m_local[r] = tM;
      state.k_byte_offset[r] = 0;
      state.cached_real_row[r] = -1;
      state.cached_row_mask[r] = 0;
    }
  }
}

/// Overload for backward compat (no smem args).
__device__ void _init_A_iterator(AIteratorState &state) const {
  // Fallback: will read from smem in _update_A_indices (slower)
  CUTLASS_PRAGMA_UNROLL
  for (int r = 0; r < kItersPerThread; ++r) {
    int vec_idx = threadIdx.x + r * MaxThreadsPerBlock;
    if (vec_idx < total_vecs_A) {
      state.m_local[r] = vec_idx / k_vecs_A;
      state.k_byte_offset[r] = (vec_idx % k_vecs_A) * kVec * sizeof(ElementInput);
      state.cached_real_row[r] = -2;  // sentinel: not cached
      state.cached_row_mask[r] = 0;
    } else {
      state.m_local[r] = tM;
      state.k_byte_offset[r] = 0;
      state.cached_real_row[r] = -2;
      state.cached_row_mask[r] = 0;
    }
  }
}

/// Resolve pair_table for current K-offset using cached row info.
/// No shared memory reads in the hot path — all from registers.
__device__ void _update_A_indices(AIteratorState &state,
                                  const int *pair_table,
                                  const int *real_rows,
                                  const uint32_t *row_masks,
                                  int N_in,
                                  int N_out,
                                  int C_in,
                                  int offset_k,
                                  int K,
                                  int stride_A = 0) const {
  if (stride_A == 0) stride_A = C_in;
  const int *pt_base = pair_table + offset_k * N_out;
  int elem_bytes = sizeof(ElementInput);

  CUTLASS_PRAGMA_UNROLL
  for (int r = 0; r < kItersPerThread; ++r) {
    int m = state.m_local[r];
    if (m < tM) {
      // Use cached values (registers) instead of smem reads
      int real_row = (state.cached_real_row[r] != -2) ? state.cached_real_row[r] : real_rows[m];
      int in_row = -1;
      {
        uint32_t _rm = (MaskWords == 1 && state.cached_real_row[r] != -2)
                           ? state.cached_row_mask[r]
                           : row_masks[m * MaskWords + offset_k / 32];
        if (real_row >= 0 && (_rm & (1u << (offset_k % 32)))) in_row = __ldg(&pt_base[real_row]);
      }
      if (in_row >= 0 && in_row < N_in) {
        state.gmem_byte_offsets[r] = in_row * stride_A * elem_bytes;
        state.valid[r] = true;
      } else {
        state.gmem_byte_offsets[r] = 0;
        state.valid[r] = false;
      }
    } else {
      state.gmem_byte_offsets[r] = 0;
      state.valid[r] = false;
    }
  }
}

/// E1 offset-index precomputation variant — reads in_row from
/// storage.precomputed_in_rows (filled by pair_table_precompute() before the
/// offset loop). Replaces the __ldg(pair_table) serialization with a smem
/// load. Caller must pass the precomputed table pointer; row_masks /
/// real_rows are unused (already folded into the precompute step).
__device__ void _update_A_indices_from_smem(AIteratorState &state,
                                            const int *precomputed_in_rows,
                                            int N_in,
                                            int C_in,
                                            int offset_k,
                                            int stride_A = 0) const {
  if (stride_A == 0) stride_A = C_in;
  int elem_bytes = sizeof(ElementInput);
  const int *pc_k = precomputed_in_rows + offset_k * tM;

  CUTLASS_PRAGMA_UNROLL
  for (int r = 0; r < kItersPerThread; ++r) {
    int m = state.m_local[r];
    if (m < tM) {
      int in_row = pc_k[m];
      if (in_row >= 0 && in_row < N_in) {
        state.gmem_byte_offsets[r] = in_row * stride_A * elem_bytes;
        state.valid[r] = true;
      } else {
        state.gmem_byte_offsets[r] = 0;
        state.valid[r] = false;
      }
    } else {
      state.gmem_byte_offsets[r] = 0;
      state.valid[r] = false;
    }
  }
}

/// Load full A tile using pre-computed addresses.
template <class SmemTensor>
__device__ void _load_A_with_offsets(const ElementInput *ptr_A,
                                     const AIteratorState &state,
                                     SmemTensor smem_tile,
                                     int k_start,
                                     int C_in,
                                     int stride_A = 0) const {
  _load_A_kblock<SmemTensor, 0>(ptr_A, state, smem_tile, k_start, C_in, stride_A);
  if constexpr (K_BLOCK_MAX_STATIC > 1)
    _load_A_kblock<SmemTensor, 1>(ptr_A, state, smem_tile, k_start, C_in, stride_A);
  if constexpr (K_BLOCK_MAX_STATIC > 2)
    _load_A_kblock<SmemTensor, 2>(ptr_A, state, smem_tile, k_start, C_in, stride_A);
  if constexpr (K_BLOCK_MAX_STATIC > 3)
    _load_A_kblock<SmemTensor, 3>(ptr_A, state, smem_tile, k_start, C_in, stride_A);
}

/// Per-kblock A load with pre-computed thread positions.
/// Eliminates vec_idx division. Uses SmemTensor for stage-correct smem addressing.
template <class SmemTensor, int KB>
__device__ void _load_A_kblock(const ElementInput *ptr_A,
                               const AIteratorState &state,
                               SmemTensor smem_tile,
                               int k_start,
                               int C_in,
                               int stride_A = 0) const {
  const char *base_ptr = reinterpret_cast<const char *>(ptr_A);
  int k_start_bytes = k_start * sizeof(ElementInput);
  // Group-conv alignment: cp.async.v4 needs 16-byte aligned source.
  // Misaligned when groups>1 AND per-group C not multiple of kVec.
  int stride_bytes = (stride_A ? stride_A : C_in) * (int)sizeof(ElementInput);
  bool ptr_A_aligned = ((reinterpret_cast<uintptr_t>(ptr_A) | (uintptr_t)stride_bytes) & 15u) == 0;
  constexpr int iters_per_kb = (kItersPerThread + K_BLOCK_MAX_STATIC - 1) / K_BLOCK_MAX_STATIC;
  CUTLASS_PRAGMA_UNROLL
  for (int i = 0; i < iters_per_kb; ++i) {
    int r = KB * iters_per_kb + i;
    if (r < kItersPerThread && state.m_local[r] < tM) {
      int m = state.m_local[r];
      int k_local = state.k_byte_offset[r] / int(sizeof(ElementInput));
      int k_global = k_start + k_local;
      uint32_t sa = cute::cast_smem_ptr_to_uint(&smem_tile(m, k_local));
      bool k_full = (k_global + kVec <= C_in);
      if (state.valid[r] && k_full && ptr_A_aligned) {
        const void *src =
            base_ptr + state.gmem_byte_offsets[r] + k_start_bytes + state.k_byte_offset[r];
        asm volatile(
            "cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(sa), "l"(src), "n"(16));
      } else {
        // Scalar fallback for invalid row OR C_in < kVec OR k-tail OR
        // misaligned (group_id * C_in not multiple of kVec elements).
        // Mirrors _load_A_identity (generate_fwd.py). Fixes the
        // silent-zero class that bit tile 42 at C_in=3, and the group-conv
        // misalignment class when groups>1.
        int4 frag = make_int4(0, 0, 0, 0);
        if (state.valid[r]) {
          const ElementInput *row_ptr =
              reinterpret_cast<const ElementInput *>(base_ptr + state.gmem_byte_offsets[r]);
          ElementInput *dst = reinterpret_cast<ElementInput *>(&frag);
          CUTLASS_PRAGMA_UNROLL
          for (int v = 0; v < kVec; ++v) {
            int k = k_global + v;
            if (k < C_in) dst[v] = row_ptr[k];
          }
        }
        asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(sa),
                     "r"(frag.x),
                     "r"(frag.y),
                     "r"(frag.z),
                     "r"(frag.w));
      }
    }
  }
}
