// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by warpgemm.codegen.generate.compose_a_loader_iter_fragment().
// DO NOT EDIT — changes will be overwritten on next codegen run.
//
// Cross-kernel A-loader fragment shared by fwd + dgrad helper fragments.
// Struct-body fragment, transitively #include'd inside per-tile struct private:.

// ---- Gathered A iterator with pre-resolved byte offsets ----

// Work distribution: total_vecs = tM * k_vecs_A, distributed round-robin across threads
static constexpr int k_vecs_A = tK / kVec;
static constexpr int total_vecs_A = tM * k_vecs_A;
// Number of vector iterations each thread performs (NOT rows — vectors!)
static constexpr int kRowsPerThread = (total_vecs_A + MaxThreadsPerBlock - 1) / MaxThreadsPerBlock;

// Pre-resolved byte offsets for gathered A rows (one per vector this thread touches)
// Resolved once per K-offset in _update_A_indices, reused for all K-tiles
struct AIteratorState {
  int byte_offsets[kRowsPerThread > 0 ? kRowsPerThread : 1];  // byte offset into ptr_A
  bool valid[kRowsPerThread > 0 ? kRowsPerThread : 1];        // bounds check
};

/// Resolve pair_table indices for the current K-offset.
/// Called once per K-offset change (not per K-tile).
/// Converts pair_table[k, real_row] → byte offset into ptr_A.
__device__ void _update_A_indices(AIteratorState &state,
                                  const int *pair_table,
                                  const int *real_rows,
                                  const uint32_t *row_masks,
                                  int N_in,
                                  int N_out,
                                  int C_in,
                                  int offset_k,
                                  int K,
                                  int stride_A = 0) const {
  if (stride_A == 0) stride_A = C_in;
  const int *pt_base = pair_table + offset_k * N_out;
  int elem_bytes = sizeof(ElementInput);

  CUTLASS_PRAGMA_UNROLL
  for (int r = 0; r < kRowsPerThread; ++r) {
    int vec_idx = threadIdx.x + r * MaxThreadsPerBlock;
    int m_local = vec_idx / k_vecs_A;

    if (m_local < tM) {
      int real_row = real_rows[m_local];
      int in_row = -1;
      if (real_row >= 0 &&
          (row_masks[m_local * MaskWords + offset_k / 32] & (1u << (offset_k % 32)))) {
        in_row = __ldg(&pt_base[real_row]);
      }
      if (in_row >= 0 && in_row < N_in) {
        state.byte_offsets[r] = in_row * stride_A * elem_bytes;
        state.valid[r] = true;
      } else {
        state.byte_offsets[r] = 0;
        state.valid[r] = false;
      }
    } else {
      state.byte_offsets[r] = 0;
      state.valid[r] = false;
    }
  }
}

/// E1 offset-index precomputation variant for the iterator loader
/// (used by the interleaved mainloop). Reads in_row from smem scratch
/// populated by pair_table_precompute() before the offset loop — no
/// __ldg serialization per offset. Replaces only the pair_table read;
/// byte-offset shape (byte_offsets[r] indexed by thread-linear vec_idx
/// → m_local division) matches _update_A_indices exactly.
__device__ void _update_A_indices_from_smem(AIteratorState &state,
                                            const int *precomputed_in_rows,
                                            int N_in,
                                            int C_in,
                                            int offset_k,
                                            int stride_A = 0) const {
  if (stride_A == 0) stride_A = C_in;
  int elem_bytes = sizeof(ElementInput);
  const int *pc_k = precomputed_in_rows + offset_k * tM;

  CUTLASS_PRAGMA_UNROLL
  for (int r = 0; r < kRowsPerThread; ++r) {
    int vec_idx = threadIdx.x + r * MaxThreadsPerBlock;
    int m_local = vec_idx / k_vecs_A;
    if (m_local < tM) {
      int in_row = pc_k[m_local];
      if (in_row >= 0 && in_row < N_in) {
        state.byte_offsets[r] = in_row * stride_A * elem_bytes;
        state.valid[r] = true;
      } else {
        state.byte_offsets[r] = 0;
        state.valid[r] = false;
      }
    } else {
      state.byte_offsets[r] = 0;
      state.valid[r] = false;
    }
  }
}

/// Load A tile — full tile (calls all per-kblock loads sequentially).
template <class SmemTensor>
__device__ void _load_A_with_offsets(const ElementInput *ptr_A,
                                     const AIteratorState &state,
                                     SmemTensor smem_tile,
                                     int k_start,
                                     int C_in,
                                     int stride_A = 0) const {
  _load_A_kblock<SmemTensor, 0>(ptr_A, state, smem_tile, k_start, C_in, stride_A);
  if (K_BLOCK_MAX_STATIC > 1)
    _load_A_kblock<SmemTensor, 1>(ptr_A, state, smem_tile, k_start, C_in, stride_A);
}

/// Per-k-block A load — template on KB for zero-branch compiled dispatch.
template <class SmemTensor, int KB>
__device__ void _load_A_kblock(const ElementInput *ptr_A,
                               const AIteratorState &state,
                               SmemTensor smem_tile,
                               int k_start,
                               int C_in,
                               int stride_A = 0) const {
  const char *base_ptr = reinterpret_cast<const char *>(ptr_A);
  int elem_bytes = sizeof(ElementInput);
  // Group-conv alignment: cp.async.v4 needs 16-byte aligned source.
  int stride_bytes = (stride_A ? stride_A : C_in) * elem_bytes;
  bool ptr_A_aligned = ((reinterpret_cast<uintptr_t>(ptr_A) | (uintptr_t)stride_bytes) & 15u) == 0;
  constexpr int iters_per_kb = (kRowsPerThread + K_BLOCK_MAX_STATIC - 1) / K_BLOCK_MAX_STATIC;
  CUTLASS_PRAGMA_UNROLL
  for (int i = 0; i < iters_per_kb; ++i) {
    int r = KB * iters_per_kb + i;
    if (r < kRowsPerThread) {
      int vec_idx = threadIdx.x + r * MaxThreadsPerBlock;
      if (vec_idx < total_vecs_A) {
        int m_local = vec_idx / k_vecs_A;
        int kv = vec_idx % k_vecs_A;
        int k_local = kv * kVec;
        int k_global = k_start + k_local;
        uint32_t sa = cute::cast_smem_ptr_to_uint(&smem_tile(m_local, k_local));
        bool k_full = (k_global + kVec <= C_in);
        if (state.valid[r] && k_full && ptr_A_aligned) {
          const void *src = base_ptr + state.byte_offsets[r] + k_global * elem_bytes;
          asm volatile(
              "cp.async.ca.shared.global.L2::128B [%0], [%1], %2;\n" ::"r"(sa), "l"(src), "n"(16));
        } else {
          // Scalar fallback for invalid row OR C_in < kVec OR k-tail OR
          // misaligned (group_id * C_in not multiple of kVec elements).
          // Mirrors _load_A_identity. Fixes silent-zero class and
          // group-conv misalignment class.
          int4 frag = make_int4(0, 0, 0, 0);
          if (state.valid[r]) {
            const ElementInput *row_ptr =
                reinterpret_cast<const ElementInput *>(base_ptr + state.byte_offsets[r]);
            ElementInput *dst = reinterpret_cast<ElementInput *>(&frag);
            CUTLASS_PRAGMA_UNROLL
            for (int v = 0; v < kVec; ++v) {
              int k = k_global + v;
              if (k < C_in) dst[v] = row_ptr[k];
            }
          }
          asm volatile("st.shared.v4.b32 [%0], {%1, %2, %3, %4};\n" ::"r"(sa),
                       "r"(frag.x),
                       "r"(frag.y),
                       "r"(frag.z),
                       "r"(frag.w));
        }
      }
    }
  }
}
